In [1]:
# ============================================
# CELLULE 1 — Imports et configuration
# ============================================
import pandas as pd
import numpy as np
import zipfile
import warnings
warnings.filterwarnings('ignore')

PATH_BEDS     = r'C:\Users\hp\healthsim-simulation\data\Beds-Open-Overnight-Web_File-Q4-2023-24-Final.xlsx'
PATH_DOCTORS  = r'C:\Users\hp\healthsim-simulation\data\NHS Workforce Statistics, March 2024 Doctors by Grade and Specialty.xlsx'
PATH_NURSES   = r'C:\Users\hp\healthsim-simulation\data\NHS Workforce Statistics, March 2024 Staff Group, Care Setting and Level (1).xlsx'
PATH_SHMI_ZIP = r'C:\Users\hp\healthsim-simulation\data\SHMI data, Apr23-Mar24.zip'
PATH_CDI      = r'C:\Users\hp\healthsim-simulation\data\Table_6_CDI_april_2023_to_march_2024-os.ods'
PATH_PROV     = r'C:\Users\hp\healthsim-simulation\data\hosp-epis-stat-admi-hosp-prov-2023-24-tab.xlsx'
PATH_ERIC     = r'C:\Users\hp\healthsim-simulation\data\ERIC - 2023_24 - Trust data.csv'
PATH_NIDC     = r'C:\Users\hp\healthsim-simulation\data\National-Imaging-Data-Collection-Asset-Count-2023-24-v1.xlsx'
PATH_ORG      = r'C:\Users\hp\healthsim-simulation\data\NHS Workforce Statistics, March 2024 England and Organisation.xlsx'

print("✅ Imports OK")
print("✅ Chemins configurés")

C:\Users\hp\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\hp\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

✅ Imports OK
✅ Chemins configurés

In [2]:
# CELLULE 2 CORRIGÉE — Vérifier les colonnes
df_beds_raw = pd.read_excel(PATH_BEDS, sheet_name='NHS Trust by Sector', header=14)
print("Colonnes disponibles :")
for col in df_beds_raw.columns:
    print(f"  - '{col}'")

Colonnes disponibles :
  - 'Unnamed: 0'
  - 'Year'
  - 'Period'
  - 'Region Code'
  - 'Org Code'
  - 'Org Name'
  - 'Total '
  - 'General & Acute'
  - 'Learning Disabilities'
  - 'Maternity'
  - 'Mental Illness'
  - 'Unnamed: 11'
  - 'Total .1'
  - 'General & Acute.1'
  - 'Learning Disabilities.1'
  - 'Maternity.1'
  - 'Mental Illness.1'
  - 'Unnamed: 17'
  - 'Total .2'
  - 'General & Acute.2'
  - 'Learning Disabilities.2'
  - 'Maternity.2'
  - 'Mental Illness.2'

In [3]:
pip install --upgrade openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [4]:
# CELLULE 2 — Chargement NHS Beds (corrigé)
df_beds_raw = pd.read_excel(PATH_BEDS, sheet_name='NHS Trust by Sector', header=14)

df_beds = df_beds_raw[['Org Code', 'Org Name',
                        'Total ', 'Total .1',
                        'Total .2']].copy()

df_beds.columns = ['Trust_code', 'Trust_name',
                   'lits_disponibles', 'lits_occupes',
                   'C2_occupation_pct']

# Garder seulement les vrais codes trust (3 caractères)
df_beds = df_beds[df_beds['Trust_code'].astype(str).str.len() == 3]

# Convertir en numérique
df_beds['lits_disponibles']  = pd.to_numeric(df_beds['lits_disponibles'], errors='coerce')
df_beds['lits_occupes']      = pd.to_numeric(df_beds['lits_occupes'], errors='coerce')
df_beds['C2_occupation_pct'] = pd.to_numeric(df_beds['C2_occupation_pct'], errors='coerce')

# Convertir en pourcentage (0.94 → 94%)
df_beds['C2_occupation_pct'] = df_beds['C2_occupation_pct'] * 100

# Calculer A8
df_beds['A8_lits_vacants_pct'] = 100 - df_beds['C2_occupation_pct']

# Supprimer lignes manquantes
df_beds = df_beds.dropna(subset=['lits_disponibles', 'C2_occupation_pct'])

print(f"✅ NHS Beds chargé : {len(df_beds)} trusts")
print(f"\nAperçu :")
print(df_beds.head(3).to_string())
print(f"\nStats C2 et A8 :")
print(df_beds[['C2_occupation_pct', 'A8_lits_vacants_pct']].describe())

✅ NHS Beds chargé : 185 trusts

Aperçu :
  Trust_code                                         Trust_name  lits_disponibles  lits_occupes  C2_occupation_pct  A8_lits_vacants_pct
2        R1H                             BARTS HEALTH NHS TRUST       2072.923077   1967.813187          94.929388             5.070612
3        R1K  LONDON NORTH WEST UNIVERSITY HEALTHCARE NHS TRUST       1089.978022   1021.153846          93.685728             6.314272
4        RAL             ROYAL FREE LONDON NHS FOUNDATION TRUST       1203.109890    922.637363          76.687705            23.312295

Stats C2 et A8 :
       C2_occupation_pct  A8_lits_vacants_pct
count         185.000000           185.000000
mean           88.559857            11.440143
std             8.028079             8.028079
min            50.240427             0.826781
25%            86.735088             6.466237
50%            90.265487             9.734513
75%            93.533763            13.264912
max            99.173219            49.759573

In [5]:
# CELLULE 3 — Vérifier les colonnes SHMI
import zipfile

with zipfile.ZipFile(PATH_SHMI_ZIP, 'r') as z:
    z.extractall(r'C:\Users\hp\healthsim-simulation\data\SHMI')

shmi_file = r'C:\Users\hp\healthsim-simulation\data\SHMI\SHMI data\SHMI_data_at_trust_level_Apr23-Mar24_csv.csv'
df_shmi = pd.read_csv(shmi_file)

print("Colonnes disponibles :")
for col in df_shmi.columns:
    print(f"  - '{col}'")

print("\nPremières lignes :")
print(df_shmi.head(3).to_string())

Colonnes disponibles :
  - 'INDICATOR_CODE'
  - 'PROVIDER_CODE'
  - 'PROVIDER_NAME'
  - 'SHMI_VALUE'
  - 'SHMI_BANDING'
  - 'SPELLS'
  - 'OBSERVED'
  - 'EXPECTED'
  - 'PO_LL'
  - 'PO_UL'
  - 'OD_LL'
  - 'OD_UL'

Premières lignes :
  INDICATOR_CODE PROVIDER_CODE                                                   PROVIDER_NAME SHMI_VALUE SHMI_BANDING  SPELLS OBSERVED EXPECTED   PO_LL   PO_UL   OD_LL   OD_UL
0         I00699           RCF                                   AIREDALE NHS FOUNDATION TRUST     0.9745            2   32270     1095     1125  0.9104  1.0956  0.8848  1.1302
1         I00699           RTK           ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATION TRUST     0.9874            2   58460     1635     1660  0.9258  1.0782  0.8888  1.1251
2         I00699           RF4  BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOSPITALS NHS TRUST     0.8984            2  115830     2645     2945   0.944  1.0583  0.8927  1.1202

In [6]:
# ============================================
# CELLULE 3 — Chargement NHS SHMI (corrigé)
# ============================================
shmi_file = r'C:\Users\hp\healthsim-simulation\data\SHMI data, Apr23-Mar24.zip'
import zipfile, os

with zipfile.ZipFile(shmi_file, 'r') as z:
    z.extractall(r'C:\Users\hp\healthsim-simulation\data\SHMI')

shmi_csv = r'C:\Users\hp\healthsim-simulation\data\SHMI\SHMI data\SHMI_data_at_trust_level_Apr23-Mar24_csv.csv'
df_shmi = pd.read_csv(shmi_csv)

df_shmi = df_shmi[['PROVIDER_CODE', 'PROVIDER_NAME',
                    'SHMI_VALUE', 'SHMI_BANDING',
                    'OBSERVED', 'EXPECTED',
                    'SPELLS']].copy()

df_shmi.columns = ['Trust_code', 'Trust_name_shmi',
                   'SHMI_VALUE', 'SHMI_banding',
                   'deces_observes', 'deces_attendus',
                   'spells_total']

# Convertir en numérique
for col in ['SHMI_VALUE', 'deces_observes', 'deces_attendus', 'spells_total']:
    df_shmi[col] = pd.to_numeric(df_shmi[col], errors='coerce')

# ✅ C3 en pourcentage — compatible HealthSim
df_shmi['C3_mortalite_pct'] = (df_shmi['deces_observes'] / 
                                df_shmi['spells_total'] * 100)

print(f"✅ NHS SHMI chargé : {len(df_shmi)} trusts")
print(f"\nAperçu :")
print(df_shmi[['Trust_code', 'C3_mortalite_pct', 'spells_total']].head(3).to_string())
print(f"\nStats C3 % :")
print(df_shmi['C3_mortalite_pct'].describe())

✅ NHS SHMI chargé : 119 trusts

Aperçu :
  Trust_code  C3_mortalite_pct  spells_total
0        RCF          3.393244       32270.0
1        RTK          2.796784       58460.0
2        RF4          2.283519      115830.0

Stats C3 % :
count    118.000000
mean       3.283792
std        0.737346
min        1.260902
25%        2.839210
50%        3.321513
75%        3.754134
max        5.408766
Name: C3_mortalite_pct, dtype: float64

In [7]:
# ============================================
# CELLULE 4 — Chargement CDI Infections (corrigé)
# ============================================
df_cdi_raw = pd.read_excel(PATH_CDI, engine='odf',
                            sheet_name='data', header=2)

df_cdi_raw.columns = ['Collection', 'Org_type', 'Org_code', 'Org_name',
                       'UKHSA', 'ICB', 'Region', 'Year', 'Month',
                       'Metric', 'Figure', 'Signed', 'Changed']

# Filtrer NHS acute trust + Total cases
df_cdi_filtered = df_cdi_raw[
    (df_cdi_raw['Org_type'] == 'NHS acute trust') &
    (df_cdi_raw['Metric'] == 'Total cases')
].copy()

df_cdi_filtered['Figure'] = pd.to_numeric(df_cdi_filtered['Figure'], errors='coerce')

# Total annuel par trust
df_cdi = df_cdi_filtered.groupby(['Org_code', 'Org_name'])['Figure'].sum().reset_index()
df_cdi.columns = ['Trust_code', 'Trust_name_cdi', 'CDI_total_cases']

# ✅ C4 en % — fusion avec spells_total depuis SHMI
df_cdi = df_cdi.merge(df_shmi[['Trust_code', 'spells_total']], 
                       on='Trust_code', how='left')

df_cdi['C4_infections_pct'] = (df_cdi['CDI_total_cases'] / 
                                df_cdi['spells_total'] * 100)

print(f"✅ NHS CDI chargé : {len(df_cdi)} trusts")
print(f"\nAperçu :")
print(df_cdi[['Trust_code', 'CDI_total_cases', 
              'spells_total', 'C4_infections_pct']].head(3).to_string())
print(f"\nStats C4 % :")
print(df_cdi['C4_infections_pct'].describe())

✅ NHS CDI chargé : 136 trusts

Aperçu :
  Trust_code  CDI_total_cases  spells_total  C4_infections_pct
0        R0A              326      188940.0           0.172542
1        R0B              111       80960.0           0.137105
2        R0D              184       97940.0           0.187870

Stats C4 % :
count    118.000000
mean       0.185913
std        0.068093
min        0.042909
25%        0.140500
50%        0.177353
75%        0.229690
max        0.421355
Name: C4_infections_pct, dtype: float64

In [8]:
pip install odfpy

Requirement already satisfied: odfpy in c:\users\hp\anaconda3\lib\site-packages (1.4.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: defusedxml in c:\users\hp\anaconda3\lib\site-packages (from odfpy) (0.7.1)

In [9]:
# ============================================
# CELLULE 5 — Chargement Hospital Providers
# ============================================
df_prov_raw = pd.read_excel(PATH_PROV, 
                             sheet_name='Hospital Providers', 
                             header=None)

# Trouver la ligne header
for i in range(30):
    row = df_prov_raw.iloc[i]
    vals = [str(v) for v in row if str(v) != 'nan']
    if len(vals) > 5:
        header_row = i
        break

print(f"Header trouvé à la ligne : {header_row}")

# Recharger avec le bon header
df_prov = pd.read_excel(PATH_PROV, 
                         sheet_name='Hospital Providers', 
                         header=header_row)

print("\nColonnes disponibles :")
for col in df_prov.columns:
    print(f"  - '{col}'")

Header trouvé à la ligne : 16

Colonnes disponibles :
  - 'Hospital provider code and description†'
  - 'Unnamed: 1'
  - 'Unnamed: 2'
  - 'Unnamed: 3'
  - 'Unnamed: 4'
  - 'Unnamed: 5'
  - 'Unnamed: 6'
  - 'Finished consultant episodes'
  - 'Finished Admission Episodes'
  - 'Male
(FCE)'
  - 'Female
(FCE)'
  - 'Gender Unknown
(FCE)'
  - 'Emergency
(FAE)'
  - 'Waiting list
(FAE)'
  - 'Planned (FAE)'
  - 'Other (FAE)'
  - 'Mean time waited
(Days)'
  - 'Median time waited
(Days)'
  - 'Mean length of stay
(Days)'
  - 'Median length of stay
(Days)'
  - 'Mean age
(Years)'
  - 'Age 0
(FCE)'
  - 'Age 1-4
(FCE)'
  - 'Age 5-9
(FCE)'
  - 'Age 10-14
(FCE)'
  - 'Age 15
(FCE)'
  - 'Age 16
(FCE)'
  - 'Age 17
(FCE)'
  - 'Age 18
(FCE)'
  - 'Age 19
(FCE)'
  - 'Age 20-24
(FCE)'
  - 'Age 25-29
(FCE)'
  - 'Age 30-34
(FCE)'
  - 'Age 35-39
(FCE)'
  - 'Age 40-44
(FCE)'
  - 'Age 45-49
(FCE)'
  - 'Age 50-54
(FCE)'
  - 'Age 55-59
(FCE)'
  - 'Age 60-64
(FCE)'
  - 'Age 65-69
(FCE)'
  - 'Age 70-74
(FCE)'
  - 'Age 75-79
(FCE)'
  - 'Age 80-84
(FCE)'
  - 'Age 85-89
(FCE)'
  - 'Age 90+
(FCE)'
  - 'Day case
(FCE)'
  - 'FCE bed days'
  - 'Emergency
(FAE).1'
  - 'Elective
(FAE)'
  - 'Other
(FAE)'

In [10]:
# ============================================
# CELLULE 5 — Chargement Hospital Providers (corrigé)
# ============================================
df_prov_raw = pd.read_excel(PATH_PROV,
                             sheet_name='Hospital Providers',
                             header=16)

# Garder colonnes utiles
df_prov = df_prov_raw[['Hospital provider code and description†',
                        'Unnamed: 1',
                        'Finished Admission Episodes',
                        'Emergency \n(FAE)',
                        'Mean length of stay \n(Days)',
                        'FCE bed days',
                        'Emergency \n(FAE).1',
                        'Elective\n(FAE)',
                        'Other\n(FAE)']].copy()

# Renommer
df_prov.columns = ['Trust_code', 'Trust_name_prov',
                   'total_admissions',
                   'emergency_fae_admission',
                   'A2_dms_jours',
                   'fce_bed_days',
                   'emergency_fae_discharge',
                   'elective_fae_discharge',
                   'other_fae_discharge']

# Garder seulement codes trust 3 caractères
df_prov = df_prov[df_prov['Trust_code'].astype(str).str.len() == 3]

# Convertir en numérique
for col in ['total_admissions', 'emergency_fae_admission',
            'A2_dms_jours', 'fce_bed_days',
            'emergency_fae_discharge', 'elective_fae_discharge',
            'other_fae_discharge']:
    df_prov[col] = pd.to_numeric(df_prov[col], errors='coerce')

# ✅ A9 corrigé — Other FAE discharge / Total × 100
df_prov['A9_taux_transfert_pct'] = (df_prov['other_fae_discharge'] /
                                     df_prov['total_admissions'] * 100)

# ✅ pct admissions urgentes
df_prov['pct_admissions_urgentes'] = (df_prov['emergency_fae_admission'] /
                                       df_prov['total_admissions'] * 100)

# Supprimer lignes manquantes
df_prov = df_prov.dropna(subset=['A2_dms_jours', 'A9_taux_transfert_pct'])

print(f"✅ Hospital Providers chargé : {len(df_prov)} trusts")
print(f"\nAperçu :")
print(df_prov[['Trust_code', 'A2_dms_jours', 
               'A9_taux_transfert_pct',
               'pct_admissions_urgentes']].head(3).to_string())
print(f"\nStats :")
print(df_prov[['A2_dms_jours', 'A9_taux_transfert_pct']].describe())

✅ Hospital Providers chargé : 150 trusts

Aperçu :
  Trust_code  A2_dms_jours  A9_taux_transfert_pct  pct_admissions_urgentes
3        Y56      5.083816               4.601895                31.061051
4        Y58      4.699411               3.137688                38.904319
5        Y59      5.771161               2.467638                40.296955

Stats :
       A2_dms_jours  A9_taux_transfert_pct
count    150.000000             150.000000
mean      16.788306               3.080022
std       45.277442               4.215239
min        0.347465               0.000000
25%        3.924706               0.795248
50%        4.482360               1.456726
75%        5.849198               4.598963
max      363.739344              38.692027

In [11]:
# ============================================
# CELLULE 6 — Médecins et Infirmiers par hôpital
# ============================================
PATH_ORG = r'C:\Users\hp\healthsim-simulation\data\NHS Workforce Statistics, March 2024 England and Organisation.xlsx'

df_org_raw = pd.read_excel(PATH_ORG, 
                            sheet_name='3. NHSE, Org & SG - FTE', 
                            header=5)

print("Colonnes disponibles :")
for col in df_org_raw.columns:
    print(f"  - '{col}'")

Colonnes disponibles :
  - 'NHS England region code'
  - 'NHS England region name'
  - 'ICS code'
  - 'ICS name'
  - 'Organisation name'
  - 'Organisation code'
  - 'Total'
  - 'Professionally qualified clinical staff'
  - 'HCHS Doctors'
  - 'Consultant'
  - 'Associate Specialist'
  - 'Specialty Doctor'
  - 'Staff Grade'
  - 'Specialty Registrar'
  - 'Core Training'
  - 'Foundation Doctor Year 2'
  - 'Foundation Doctor Year 1'
  - 'Hospital Practitioner / Clinical Assistant'
  - 'Other and Local HCHS Doctor Grades'
  - 'Nurses & health visitors'
  - 'Midwives'
  - 'Ambulance staff'
  - 'Scientific, therapeutic & technical staff'
  - 'Support to clinical staff'
  - 'Support to doctors, nurses & midwives'
  - 'Support to ambulance staff'
  - 'Support to ST&T staff'
  - 'NHS infrastructure support'
  - 'Central functions'
  - 'Hotel, property & estates'
  - 'Senior managers'
  - 'Managers'
  - 'Other staff or those with unknown classification'

In [12]:
# ============================================
# CELLULE 5B — Chargement A4 depuis AEQI
# ============================================
import requests
import io

url = "https://files.digital.nhs.uk/23/C1A9E0/aeqi_open_data_2024_03.csv"
print("Téléchargement AEQI...")
response = requests.get(url, timeout=120)
df_aeqi = pd.read_csv(io.StringIO(response.content.decode('utf-8')))
print(f"✅ AEQI chargé : {df_aeqi.shape}")

# Filtrer année 2023-24
df_aeqi['ATTENDANCE_MONTH'] = pd.to_datetime(df_aeqi['ATTENDANCE_MONTH'])
df_2324 = df_aeqi[
    (df_aeqi['ATTENDANCE_MONTH'] >= '2023-04-01') &
    (df_aeqi['ATTENDANCE_MONTH'] <= '2024-03-31')
].copy()

# Extraire TOTAL_TIME_MEDIAN par trust
df_a4 = df_2324[df_2324['MEASURE_NAME'] == 'TOTAL_TIME_MEDIAN'].copy()
df_a4['MEASURE_VALUE'] = pd.to_numeric(df_a4['MEASURE_VALUE'], errors='coerce')

# Moyenne annuelle par trust
df_a4 = df_a4.groupby(['ORG_CODE', 'ORG_NAME'])['MEASURE_VALUE'].mean().reset_index()
df_a4.columns = ['Trust_code', 'Trust_name_a4', 'A4_temps_attente_min']

# Garder seulement codes 3 caractères
df_a4 = df_a4[df_a4['Trust_code'].astype(str).str.len() == 3]

print(f"\n✅ A4 chargé : {len(df_a4)} trusts")
print(f"\nAperçu :")
print(df_a4.head(3).to_string())
print(f"\nStats A4 (minutes) :")
print(df_a4['A4_temps_attente_min'].describe())

Téléchargement AEQI...
✅ AEQI chargé : (96693, 7)

✅ A4 chargé : 151 trusts

Aperçu :
  Trust_code                        Trust_name_a4  A4_temps_attente_min
1        91Q        NHS KENT AND MEDWAY ICB - 91Q                169.00
5        AH6  URGENT CARE CENTRE- HURLEY GROUP HQ                114.25
6        ANH                       MALLING HEALTH                 81.75

Stats A4 (minutes) :
count    151.000000
mean     176.546973
std       55.245242
min       20.944444
25%      149.791667
50%      184.583333
75%      215.729167
max      331.500000
Name: A4_temps_attente_min, dtype: float64

In [13]:
# ============================================
# CELLULE 7 — Chargement NIDC Équipements (corrigé)
# ============================================
df_nidc = pd.read_excel(PATH_NIDC,
                        sheet_name='ICB, Imaging Network and Trust',
                        header=13)

# Garder seulement trusts avec ODS code
df_nidc = df_nidc[df_nidc['Organisation Code'].notna()].copy()
df_nidc = df_nidc[df_nidc['Organisation Code'].astype(str).str.len() == 3]

# Garder colonnes utiles
df_nidc = df_nidc[['Organisation Code', 'Organisation Name', 'Total']].copy()
df_nidc.columns = ['Trust_code', 'Trust_name_nidc', 'equipements_total']

# Convertir en numérique
df_nidc['equipements_total'] = pd.to_numeric(df_nidc['equipements_total'], errors='coerce')

# ✅ D5 ratio = équipements / lits — fusion avec df_beds
df_nidc = df_nidc.merge(df_beds[['Trust_code', 'lits_disponibles']],
                         on='Trust_code', how='left')

df_nidc['D5_ratio_equipement_lit'] = (df_nidc['equipements_total'] /
                                       df_nidc['lits_disponibles'])

print(f"✅ NIDC chargé : {len(df_nidc)} trusts")
print(f"\nAperçu :")
print(df_nidc[['Trust_code', 'equipements_total',
               'lits_disponibles', 'D5_ratio_equipement_lit']].head(5).to_string())
print(f"\nStats D5 ratio :")
print(df_nidc['D5_ratio_equipement_lit'].describe())

✅ NIDC chargé : 138 trusts

Aperçu :
  Trust_code  equipements_total  lits_disponibles  D5_ratio_equipement_lit
0        RP4               41.0        212.197802                 0.193216
1        RP6               26.0          7.032967                 3.696875
2        RAP               46.0        457.010989                 0.100654
3        RAL              155.0       1203.109890                 0.128833
4        RAN               33.0        133.736264                 0.246754

Stats D5 ratio :
count    136.000000
mean       0.135158
std        0.312679
min        0.029676
25%        0.081515
50%        0.096144
75%        0.119476
max        3.696875
Name: D5_ratio_equipement_lit, dtype: float64

In [14]:
# ============================================
# CELLULE 6 — Workforce + Ratios B7 (corrigé)
# ============================================
PATH_ORG = r'C:\Users\hp\healthsim-simulation\data\NHS Workforce Statistics, March 2024 England and Organisation.xlsx'

df_org = pd.read_excel(PATH_ORG,
                       sheet_name='3. NHSE, Org & SG - FTE',
                       header=5)

df_org = df_org[df_org['Organisation code'].notna()].copy()

df_workforce = df_org[['Organisation code', 'Organisation name',
                        'HCHS Doctors',
                        'Nurses & health visitors']].copy()

df_workforce.columns = ['Trust_code', 'Trust_name_workforce',
                         'B7_medecins_fte',
                         'B7_infirmiers_fte']

df_workforce['B7_medecins_fte']  = pd.to_numeric(df_workforce['B7_medecins_fte'], errors='coerce')
df_workforce['B7_infirmiers_fte'] = pd.to_numeric(df_workforce['B7_infirmiers_fte'], errors='coerce')

df_workforce = df_workforce.dropna(subset=['B7_medecins_fte', 'B7_infirmiers_fte'])

df_workforce = df_workforce.merge(df_beds[['Trust_code', 'lits_disponibles']],
                                   on='Trust_code', how='left')

df_workforce['ratio_medecin_lit']   = (df_workforce['B7_medecins_fte'] /
                                        df_workforce['lits_disponibles'])
df_workforce['ratio_infirmier_lit'] = (df_workforce['B7_infirmiers_fte'] /
                                        df_workforce['lits_disponibles'])
df_workforce['ratio_infirmier_medecin'] = (df_workforce['B7_infirmiers_fte'] /
                                            df_workforce['B7_medecins_fte'])

# ✅ Nettoyage valeurs infinies et NaN
import numpy as np
df_workforce = df_workforce.replace([np.inf, -np.inf], np.nan)
df_workforce = df_workforce.dropna(subset=['ratio_medecin_lit',
                                            'ratio_infirmier_lit',
                                            'ratio_infirmier_medecin'])

print(f"✅ Workforce après nettoyage : {len(df_workforce)} trusts")
print(f"\nStats ratios corrigés :")
print(df_workforce[['ratio_medecin_lit',
                     'ratio_infirmier_lit',
                     'ratio_infirmier_medecin']].describe())

✅ Workforce après nettoyage : 185 trusts

Stats ratios corrigés :
       ratio_medecin_lit  ratio_infirmier_lit  ratio_infirmier_medecin
count         185.000000           185.000000               185.000000
mean            1.254790             3.364936                 4.061383
std             3.346524             5.113050                 6.890043
min             0.227587             1.478030                 1.155283
25%             0.777922             2.101688                 2.034533
50%             0.962282             2.471369                 2.339023
75%             1.198346             3.259895                 3.584434
max            46.084730            63.453693                82.488939

In [15]:
# ============================================
# CELLULE 8 — FUSION DE TOUS LES FICHIERS
# ============================================

# Base de fusion = SHMI (119 trusts — le plus restrictif)
# On utilise SHMI comme base car il contient exactement les trusts
# qu'on veut dans notre dataset final
df_final = df_shmi[['Trust_code', 'Trust_name_shmi',
                     'C3_mortalite_pct', 'SHMI_VALUE',
                     'spells_total', 'deces_observes']].copy()
print(f"Base SHMI : {len(df_final)} trusts")

# ── Fusion 1 : NHS Beds (A8, C2, lits_disponibles) ──
df_final = df_final.merge(
    df_beds[['Trust_code', 'lits_disponibles',
             'C2_occupation_pct', 'A8_lits_vacants_pct']],
    on='Trust_code', how='left')
print(f"Après Beds : {df_final['C2_occupation_pct'].notna().sum()} trusts avec données")

# ── Fusion 2 : CDI (C4) ──
df_final = df_final.merge(
    df_cdi[['Trust_code', 'CDI_total_cases', 'C4_infections_pct']],
    on='Trust_code', how='left')
print(f"Après CDI : {df_final['C4_infections_pct'].notna().sum()} trusts avec données")

# ── Fusion 3 : Hospital Providers (A2, A9) ──
df_final = df_final.merge(
    df_prov[['Trust_code', 'A2_dms_jours',
             'A9_taux_transfert_pct',
             'total_admissions',
             'pct_admissions_urgentes']],
    on='Trust_code', how='left')
print(f"Après Providers : {df_final['A2_dms_jours'].notna().sum()} trusts avec données")

# ── Fusion 4 : AEQI (A4) ──
df_final = df_final.merge(
    df_a4[['Trust_code', 'A4_temps_attente_min']],
    on='Trust_code', how='left')
print(f"Après AEQI : {df_final['A4_temps_attente_min'].notna().sum()} trusts avec données")

# ── Fusion 5 : Workforce (B7, ratios) ──
df_final = df_final.merge(
    df_workforce[['Trust_code', 'B7_medecins_fte', 'B7_infirmiers_fte',
                  'ratio_medecin_lit', 'ratio_infirmier_lit',
                  'ratio_infirmier_medecin']],
    on='Trust_code', how='left')
print(f"Après Workforce : {df_final['B7_medecins_fte'].notna().sum()} trusts avec données")

# ── Fusion 6 : NIDC (D5) ──
df_final = df_final.merge(
    df_nidc[['Trust_code', 'equipements_total', 'D5_ratio_equipement_lit']],
    on='Trust_code', how='left')
print(f"Après NIDC : {df_final['D5_ratio_equipement_lit'].notna().sum()} trusts avec données")

print(f"\n✅ Dataset fusionné : {len(df_final)} lignes × {len(df_final.columns)} colonnes")
print(f"\nColonnes :")
for col in df_final.columns:
    print(f"  - {col}")
print(f"\nValeurs manquantes :")
print(df_final.isnull().sum())

Base SHMI : 119 trusts
Après Beds : 119 trusts avec données
Après CDI : 118 trusts avec données
Après Providers : 104 trusts avec données
Après AEQI : 119 trusts avec données
Après Workforce : 119 trusts avec données
Après NIDC : 119 trusts avec données

✅ Dataset fusionné : 119 lignes × 23 colonnes

Colonnes :
  - Trust_code
  - Trust_name_shmi
  - C3_mortalite_pct
  - SHMI_VALUE
  - spells_total
  - deces_observes
  - lits_disponibles
  - C2_occupation_pct
  - A8_lits_vacants_pct
  - CDI_total_cases
  - C4_infections_pct
  - A2_dms_jours
  - A9_taux_transfert_pct
  - total_admissions
  - pct_admissions_urgentes
  - A4_temps_attente_min
  - B7_medecins_fte
  - B7_infirmiers_fte
  - ratio_medecin_lit
  - ratio_infirmier_lit
  - ratio_infirmier_medecin
  - equipements_total
  - D5_ratio_equipement_lit

Valeurs manquantes :
Trust_code                  0
Trust_name_shmi             0
C3_mortalite_pct            1
SHMI_VALUE                  1
spells_total                1
deces_observes              1
lits_disponibles            0
C2_occupation_pct           0
A8_lits_vacants_pct         0
CDI_total_cases             0
C4_infections_pct           1
A2_dms_jours               15
A9_taux_transfert_pct      15
total_admissions           15
pct_admissions_urgentes    15
A4_temps_attente_min        0
B7_medecins_fte             0
B7_infirmiers_fte           0
ratio_medecin_lit           0
ratio_infirmier_lit         0
ratio_infirmier_medecin     0
equipements_total           0
D5_ratio_equipement_lit     0
dtype: int64

In [16]:
# ============================================
# CELLULE 9 — NETTOYAGE VALEURS MANQUANTES
# ============================================

print(f"Dataset avant nettoyage : {len(df_final)} trusts")
print(f"Valeurs manquantes par colonne :")
print(df_final.isnull().sum()[df_final.isnull().sum() > 0])

# Supprimer les lignes avec valeurs manquantes
# car on ne peut pas entraîner XGBoost avec des NaN
df_final = df_final.dropna()

print(f"\n✅ Dataset après nettoyage : {len(df_final)} trusts")
print(f"\nVérification — valeurs manquantes restantes :")
print(df_final.isnull().sum().sum())

print(f"\nAperçu du dataset final :")
print(df_final[['Trust_code', 'Trust_name_shmi',
                'C2_occupation_pct', 'C3_mortalite_pct',
                'A2_dms_jours', 'A4_temps_attente_min',
                'ratio_medecin_lit']].head(5).to_string())

print(f"\nStats générales :")
features = ['A2_dms_jours', 'A4_temps_attente_min', 
            'A8_lits_vacants_pct', 'A9_taux_transfert_pct',
            'C2_occupation_pct', 'C3_mortalite_pct',
            'C4_infections_pct', 'ratio_medecin_lit',
            'ratio_infirmier_lit', 'ratio_infirmier_medecin',
            'D5_ratio_equipement_lit', 'pct_admissions_urgentes']
print(df_final[features].describe())

Dataset avant nettoyage : 119 trusts
Valeurs manquantes par colonne :
C3_mortalite_pct            1
SHMI_VALUE                  1
spells_total                1
deces_observes              1
C4_infections_pct           1
A2_dms_jours               15
A9_taux_transfert_pct      15
total_admissions           15
pct_admissions_urgentes    15
dtype: int64

✅ Dataset après nettoyage : 103 trusts

Vérification — valeurs manquantes restantes :
0

Aperçu du dataset final :
  Trust_code                                                 Trust_name_shmi  C2_occupation_pct  C3_mortalite_pct  A2_dms_jours  A4_temps_attente_min  ratio_medecin_lit
0        RCF                                   AIREDALE NHS FOUNDATION TRUST          86.250102          3.393244      4.027666            222.375000           0.834860
1        RTK           ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATION TRUST          86.468412          2.796784      3.144720            210.750000           1.256611
2        RF4  BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOSPITALS NHS TRUST          94.765719          2.283519      3.516111            239.625000           1.216217
3        RFF                          BARNSLEY HOSPITAL NHS FOUNDATION TRUST          92.407288          3.227711      3.644835            206.333333           0.828729
4        R1H                                          BARTS HEALTH NHS TRUST          94.929388          2.722792      5.373930            231.000000           1.428163

Stats générales :
       A2_dms_jours  A4_temps_attente_min  A8_lits_vacants_pct  \
count    103.000000            103.000000           103.000000
mean       4.331604            197.473007             9.525908
std        0.896776             41.369666             4.433750
min        2.740721             80.750000             0.826781
25%        3.715888            176.083333             6.214148
50%        4.255169            199.500000             8.863330
75%        4.705990            221.083333            12.005526
max        7.059913            331.500000            24.861837

       A9_taux_transfert_pct  C2_occupation_pct  C3_mortalite_pct  \
count             103.000000         103.000000        103.000000
mean                3.646774          90.474092          3.279872
std                 3.193180           4.433750          0.731761
min                 0.013649          75.138163          1.260902
25%                 1.200419          87.994474          2.842105
50%                 1.889254          91.136670          3.302611
75%                 5.578757          93.785852          3.750865
max                13.530258          99.173219          5.408766

       C4_infections_pct  ratio_medecin_lit  ratio_infirmier_lit  \
count         103.000000         103.000000           103.000000
mean            0.185608           1.107335             2.410379
std             0.063065           0.273630             0.534408
min             0.055837           0.704223             1.525926
25%             0.141778           0.919678             2.076127
50%             0.178330           1.032636             2.305895
75%             0.229495           1.241423             2.636641
max             0.368764           2.136128             5.055686

       ratio_infirmier_medecin  D5_ratio_equipement_lit  \
count               103.000000               103.000000
mean                  2.222267                 0.098348
std                   0.416111                 0.026230
min                   1.552436                 0.052113
25%                   1.948170                 0.080052
50%                   2.136129                 0.092592
75%                   2.377976                 0.114415
max                   4.033939                 0.215436

       pct_admissions_urgentes
count               103.000000
mean                 40.925693
std                   7.287606
min                  12.111486
25%                  36.917868
50%                  41.691070
75%                  46.101989
max                  59.219070

In [17]:
# ============================================
# CELLULE 10 — CALCUL DU LABEL STATUT
# ============================================
# Références officielles :
# - Seuil C2 92% : NHS Operational Planning Guidance 2023-24
# - Seuil SHMI 1.15 : NHS Digital SHMI Methodology
# - Seuil A4 240 min : NHS Constitution Standard (4 heures)
# - Seuil A2 4.5 jours : NHS HES Annual Statistics 2023-24
# - Seuil A9 5% : calculé depuis Hospital Providers 2023-24
# - Règle agrégation : CQC NHS Ratings Methodology (2024)

def calculer_statut(row):
    C2   = row['C2_occupation_pct']      # depuis df_beds
    SHMI = row['SHMI_VALUE']             # depuis df_shmi
    A2   = row['A2_dms_jours']           # depuis df_prov
    A4   = row['A4_temps_attente_min']   # depuis df_a4
    A9   = row['A9_taux_transfert_pct']  # depuis df_prov

    critique  = 0
    attention = 0

    # C2 — seuil NHS 92%
    if C2 > 92:    critique  += 1
    elif C2 > 85:  attention += 1

    # SHMI — seuil NHS 1.15
    if SHMI > 1.15:   critique  += 1
    elif SHMI > 1.0:  attention += 1

    # A2 — seuil 4.5 jours
    if A2 > 7:     critique  += 1
    elif A2 > 4.5: attention += 1

    # A4 — seuil NHS Constitution 240 min
    if A4 > 720:   critique  += 1
    elif A4 > 240: attention += 1

    # A9 — seuil 5%
    if A9 > 5:    critique  += 1
    elif A9 > 2:  attention += 1

    # Règle CQC NHS (2024)
    if critique >= 2:
        return 0  # Critique
    elif critique >= 1 or attention >= 2:
        return 1  # Attention
    else:
        return 2  # Normal

# Application sur df_final
df_final['statut'] = df_final.apply(calculer_statut, axis=1)

# Mapping lisible
statut_map = {0: 'Critique', 1: 'Attention', 2: 'Normal'}
df_final['statut_label'] = df_final['statut'].map(statut_map)

print("✅ Labels calculés !")
print(f"\nDistribution des statuts :")
print(df_final['statut_label'].value_counts())
print(f"\nEn pourcentage :")
print((df_final['statut_label'].value_counts(normalize=True) * 100).round(1))

✅ Labels calculés !

Distribution des statuts :
statut_label
Attention    73
Critique     20
Normal       10
Name: count, dtype: int64

En pourcentage :
statut_label
Attention    70.9
Critique     19.4
Normal        9.7
Name: proportion, dtype: float64

In [18]:
# ============================================
# CELLULE 11 — FONCTION CHARGEMENT PAR ANNÉE
# ============================================
import zipfile, os, requests, io
import numpy as np

def charger_annee(annee, paths):
    """
    Charge et fusionne tous les fichiers NHS pour une année donnée
    annee : str ex '2023-24' ou '2022-23'
    paths : dict avec les chemins des fichiers
    """
    print(f"\n{'='*50}")
    print(f"Chargement année {annee}...")
    print(f"{'='*50}")
    
    # ── 1. NHS Beds ──
    df_beds = pd.read_excel(paths['beds'], 
                            sheet_name='NHS Trust by Sector', header=14)
    df_beds = df_beds[['Org Code', 'Org Name', 'Total ', 'Total .1', 'Total .2']].copy()
    df_beds.columns = ['Trust_code', 'Trust_name', 'lits_disponibles', 
                       'lits_occupes', 'C2_occupation_pct']
    df_beds = df_beds[df_beds['Trust_code'].astype(str).str.len() == 3]
    df_beds['lits_disponibles']  = pd.to_numeric(df_beds['lits_disponibles'], errors='coerce')
    df_beds['C2_occupation_pct'] = pd.to_numeric(df_beds['C2_occupation_pct'], errors='coerce') * 100
    df_beds['A8_lits_vacants_pct'] = 100 - df_beds['C2_occupation_pct']
    df_beds = df_beds.dropna(subset=['lits_disponibles', 'C2_occupation_pct'])
    print(f"✅ Beds : {len(df_beds)} trusts")

    # ── 2. NHS SHMI ──
    shmi_extract = f'C:\\Users\\hp\\healthsim-simulation\\data\\SHMI_{annee}'
    with zipfile.ZipFile(paths['shmi'], 'r') as z:
        z.extractall(shmi_extract)
    
    shmi_file = None
    for root, dirs, files in os.walk(shmi_extract):
        for f in files:
            if 'trust_level' in f.lower():
                shmi_file = os.path.join(root, f)
    
    df_shmi = pd.read_csv(shmi_file)
    df_shmi = df_shmi[['PROVIDER_CODE', 'PROVIDER_NAME', 'SHMI_VALUE', 
                        'SHMI_BANDING', 'OBSERVED', 'EXPECTED', 'SPELLS']].copy()
    df_shmi.columns = ['Trust_code', 'Trust_name_shmi', 'SHMI_VALUE', 
                       'SHMI_banding', 'deces_observes', 'deces_attendus', 'spells_total']
    for col in ['SHMI_VALUE', 'deces_observes', 'deces_attendus', 'spells_total']:
        df_shmi[col] = pd.to_numeric(df_shmi[col], errors='coerce')
    df_shmi['C3_mortalite_pct'] = df_shmi['deces_observes'] / df_shmi['spells_total'] * 100
    print(f"✅ SHMI : {len(df_shmi)} trusts")

    # ── 3. CDI ──
    df_cdi_raw = pd.read_excel(paths['cdi'], engine='odf', 
                                sheet_name='data', header=2)
    df_cdi_raw.columns = ['Collection', 'Org_type', 'Org_code', 'Org_name',
                           'UKHSA', 'ICB', 'Region', 'Year', 'Month',
                           'Metric', 'Figure', 'Signed', 'Changed']
    df_cdi_filtered = df_cdi_raw[
        (df_cdi_raw['Org_type'] == 'NHS acute trust') &
        (df_cdi_raw['Metric'] == 'Total cases')
    ].copy()
    df_cdi_filtered['Figure'] = pd.to_numeric(df_cdi_filtered['Figure'], errors='coerce')
    df_cdi = df_cdi_filtered.groupby(['Org_code', 'Org_name'])['Figure'].sum().reset_index()
    df_cdi.columns = ['Trust_code', 'Trust_name_cdi', 'CDI_total_cases']
    df_cdi = df_cdi.merge(df_shmi[['Trust_code', 'spells_total']], on='Trust_code', how='left')
    df_cdi['C4_infections_pct'] = df_cdi['CDI_total_cases'] / df_cdi['spells_total'] * 100
    print(f"✅ CDI : {len(df_cdi)} trusts")

    # ── 4. Hospital Providers ──
    df_prov_raw = pd.read_excel(paths['prov'], 
                                 sheet_name='Hospital Providers', header=16)
    df_prov = df_prov_raw[['Hospital provider code and description†',
                            'Unnamed: 1', 'Finished Admission Episodes',
                            'Emergency \n(FAE)', 'Mean length of stay \n(Days)',
                            'FCE bed days', 'Emergency \n(FAE).1',
                            'Elective\n(FAE)', 'Other\n(FAE)']].copy()
    df_prov.columns = ['Trust_code', 'Trust_name_prov', 'total_admissions',
                       'emergency_fae_admission', 'A2_dms_jours', 'fce_bed_days',
                       'emergency_fae_discharge', 'elective_fae_discharge', 'other_fae_discharge']
    df_prov = df_prov[df_prov['Trust_code'].astype(str).str.len() == 3]
    for col in ['total_admissions', 'A2_dms_jours', 'other_fae_discharge', 
                'emergency_fae_admission']:
        df_prov[col] = pd.to_numeric(df_prov[col], errors='coerce')
    df_prov['A9_taux_transfert_pct'] = df_prov['other_fae_discharge'] / df_prov['total_admissions'] * 100
    df_prov['pct_admissions_urgentes'] = df_prov['emergency_fae_admission'] / df_prov['total_admissions'] * 100
    df_prov = df_prov.dropna(subset=['A2_dms_jours', 'A9_taux_transfert_pct'])
    print(f"✅ Hospital Providers : {len(df_prov)} trusts")

    # ── 5. AEQI ──
    url_aeqi = paths['aeqi']
    response = requests.get(url_aeqi, timeout=120)
    df_aeqi = pd.read_csv(io.StringIO(response.content.decode('utf-8')))
    df_aeqi['ATTENDANCE_MONTH'] = pd.to_datetime(df_aeqi['ATTENDANCE_MONTH'])
    df_a4 = df_aeqi[df_aeqi['MEASURE_NAME'] == 'TOTAL_TIME_MEDIAN'].copy()
    df_a4['MEASURE_VALUE'] = pd.to_numeric(df_a4['MEASURE_VALUE'], errors='coerce')
    df_a4 = df_a4.groupby(['ORG_CODE', 'ORG_NAME'])['MEASURE_VALUE'].mean().reset_index()
    df_a4.columns = ['Trust_code', 'Trust_name_a4', 'A4_temps_attente_min']
    df_a4 = df_a4[df_a4['Trust_code'].astype(str).str.len() == 3]
    print(f"✅ AEQI : {len(df_a4)} trusts")

    # ── 6. Workforce ──
    df_org = pd.read_excel(paths['workforce'], 
                            sheet_name='3. NHSE, Org & SG - FTE', header=5)
    df_org = df_org[df_org['Organisation code'].notna()].copy()
    df_workforce = df_org[['Organisation code', 'Organisation name',
                            'HCHS Doctors', 'Nurses & health visitors']].copy()
    df_workforce.columns = ['Trust_code', 'Trust_name_workforce',
                             'B7_medecins_fte', 'B7_infirmiers_fte']
    df_workforce['B7_medecins_fte']  = pd.to_numeric(df_workforce['B7_medecins_fte'], errors='coerce')
    df_workforce['B7_infirmiers_fte'] = pd.to_numeric(df_workforce['B7_infirmiers_fte'], errors='coerce')
    df_workforce = df_workforce.dropna()
    df_workforce = df_workforce.merge(df_beds[['Trust_code', 'lits_disponibles']], 
                                       on='Trust_code', how='left')
    df_workforce['ratio_medecin_lit']       = df_workforce['B7_medecins_fte'] / df_workforce['lits_disponibles']
    df_workforce['ratio_infirmier_lit']     = df_workforce['B7_infirmiers_fte'] / df_workforce['lits_disponibles']
    df_workforce['ratio_infirmier_medecin'] = df_workforce['B7_infirmiers_fte'] / df_workforce['B7_medecins_fte']
    df_workforce = df_workforce.replace([np.inf, -np.inf], np.nan).dropna(
        subset=['ratio_medecin_lit', 'ratio_infirmier_lit', 'ratio_infirmier_medecin'])
    print(f"✅ Workforce : {len(df_workforce)} trusts")

    # ── 7. NIDC ──
    df_nidc = pd.read_excel(paths['nidc'], 
                             sheet_name='ICB, Imaging Network and Trust', header=13)
    df_nidc = df_nidc[df_nidc['Organisation Code'].notna()].copy()
    df_nidc = df_nidc[df_nidc['Organisation Code'].astype(str).str.len() == 3]
    df_nidc = df_nidc[['Organisation Code', 'Organisation Name', 'Total']].copy()
    df_nidc.columns = ['Trust_code', 'Trust_name_nidc', 'equipements_total']
    df_nidc['equipements_total'] = pd.to_numeric(df_nidc['equipements_total'], errors='coerce')
    df_nidc = df_nidc.merge(df_beds[['Trust_code', 'lits_disponibles']], 
                             on='Trust_code', how='left')
    df_nidc['D5_ratio_equipement_lit'] = df_nidc['equipements_total'] / df_nidc['lits_disponibles']
    print(f"✅ NIDC : {len(df_nidc)} trusts")

    # ── FUSION ──
    df = df_shmi[['Trust_code', 'Trust_name_shmi', 'C3_mortalite_pct', 
                   'SHMI_VALUE', 'spells_total', 'deces_observes']].copy()
    df = df.merge(df_beds[['Trust_code', 'lits_disponibles', 'C2_occupation_pct', 
                            'A8_lits_vacants_pct']], on='Trust_code', how='left')
    df = df.merge(df_cdi[['Trust_code', 'CDI_total_cases', 'C4_infections_pct']], 
                  on='Trust_code', how='left')
    df = df.merge(df_prov[['Trust_code', 'A2_dms_jours', 'A9_taux_transfert_pct',
                            'total_admissions', 'pct_admissions_urgentes']], 
                  on='Trust_code', how='left')
    df = df.merge(df_a4[['Trust_code', 'A4_temps_attente_min']], 
                  on='Trust_code', how='left')
    df = df.merge(df_workforce[['Trust_code', 'B7_medecins_fte', 'B7_infirmiers_fte',
                                 'ratio_medecin_lit', 'ratio_infirmier_lit', 
                                 'ratio_infirmier_medecin']], 
                  on='Trust_code', how='left')
    df = df.merge(df_nidc[['Trust_code', 'equipements_total', 'D5_ratio_equipement_lit']], 
                  on='Trust_code', how='left')
    
    # Nettoyage
    df = df.dropna()
    df['annee'] = annee
    
    print(f"\n✅ Dataset {annee} : {len(df)} trusts × {len(df.columns)} colonnes")
    return df

print("✅ Fonction définie !")

✅ Fonction définie !

In [19]:
# ============================================
# CELLULE 11 — FONCTION CHARGEMENT PAR ANNÉE
# ============================================
import zipfile, os, requests, io
import numpy as np

def charger_annee(annee, paths):
    print(f"\n{'='*50}")
    print(f"Chargement année {annee}...")
    print(f"{'='*50}")
    
    # ── 1. NHS Beds ──
    df_beds = pd.read_excel(paths['beds'], 
                            sheet_name='NHS Trust by Sector', header=14)
    df_beds = df_beds[['Org Code', 'Org Name', 'Total ', 'Total .1', 'Total .2']].copy()
    df_beds.columns = ['Trust_code', 'Trust_name', 'lits_disponibles', 
                       'lits_occupes', 'C2_occupation_pct']
    df_beds = df_beds[df_beds['Trust_code'].astype(str).str.len() == 3]
    df_beds['lits_disponibles']  = pd.to_numeric(df_beds['lits_disponibles'], errors='coerce')
    df_beds['C2_occupation_pct'] = pd.to_numeric(df_beds['C2_occupation_pct'], errors='coerce') * 100
    df_beds['A8_lits_vacants_pct'] = 100 - df_beds['C2_occupation_pct']
    df_beds = df_beds.dropna(subset=['lits_disponibles', 'C2_occupation_pct'])
    print(f"✅ Beds : {len(df_beds)} trusts")

    # ── 2. NHS SHMI ──
    shmi_extract = rf'C:\Users\hp\healthsim-simulation\data\SHMI_{annee}'
    with zipfile.ZipFile(paths['shmi'], 'r') as z:
        z.extractall(shmi_extract)
    
    shmi_file = None
    for root, dirs, files in os.walk(shmi_extract):
        for f in files:
            if ('shmi data at trust level' in f.lower() or
                'shmi_data_at_trust' in f.lower()) and f.endswith('.csv'):
                shmi_file = os.path.join(root, f)
                print(f"  Fichier SHMI trouvé : {f}")

    df_shmi = pd.read_csv(shmi_file, encoding='latin-1')
    df_shmi = df_shmi[['PROVIDER_CODE', 'PROVIDER_NAME', 'SHMI_VALUE', 
                        'SHMI_BANDING', 'OBSERVED', 'EXPECTED', 'SPELLS']].copy()
    df_shmi.columns = ['Trust_code', 'Trust_name_shmi', 'SHMI_VALUE', 
                       'SHMI_banding', 'deces_observes', 'deces_attendus', 'spells_total']
    for col in ['SHMI_VALUE', 'deces_observes', 'deces_attendus', 'spells_total']:
        df_shmi[col] = pd.to_numeric(df_shmi[col], errors='coerce')
    df_shmi['C3_mortalite_pct'] = df_shmi['deces_observes'] / df_shmi['spells_total'] * 100
    print(f"✅ SHMI : {len(df_shmi)} trusts")

    # ── 3. CDI ──
    df_cdi_raw = pd.read_excel(paths['cdi'], engine='odf', 
                                sheet_name='data', header=2)
    df_cdi_raw.columns = ['Collection', 'Org_type', 'Org_code', 'Org_name',
                           'UKHSA', 'ICB', 'Region', 'Year', 'Month',
                           'Metric', 'Figure', 'Signed', 'Changed']
    df_cdi_filtered = df_cdi_raw[
        (df_cdi_raw['Org_type'] == 'NHS acute trust') &
        (df_cdi_raw['Metric'] == 'Total cases')
    ].copy()
    df_cdi_filtered['Figure'] = pd.to_numeric(df_cdi_filtered['Figure'], errors='coerce')
    df_cdi = df_cdi_filtered.groupby(['Org_code', 'Org_name'])['Figure'].sum().reset_index()
    df_cdi.columns = ['Trust_code', 'Trust_name_cdi', 'CDI_total_cases']
    df_cdi = df_cdi.merge(df_shmi[['Trust_code', 'spells_total']], on='Trust_code', how='left')
    df_cdi['C4_infections_pct'] = df_cdi['CDI_total_cases'] / df_cdi['spells_total'] * 100
    print(f"✅ CDI : {len(df_cdi)} trusts")

    # ── 4. Hospital Providers ──
    df_prov_raw = pd.read_excel(paths['prov'],
                                 sheet_name='Hospital Providers', header=16)
    cols = df_prov_raw.columns.tolist()
    
    if 'Finished Admission Episodes' in cols:
        # Format 2023-24
        df_prov = df_prov_raw[['Hospital provider code and description†',
                                'Unnamed: 1', 'Finished Admission Episodes',
                                'Emergency \n(FAE)', 'Mean length of stay \n(Days)',
                                'FCE bed days', 'Emergency \n(FAE).1',
                                'Elective\n(FAE)', 'Other\n(FAE)']].copy()
    else:
        # Format 2022-23
        df_prov = df_prov_raw[['Hospital provider code and description†',
                                'Unnamed: 1', 'Admissions',
                                'Emergency', 'Mean length of stay',
                                'FCE bed days', 'Emergency.1',
                                'Elective', 'Other']].copy()

    df_prov.columns = ['Trust_code', 'Trust_name_prov', 'total_admissions',
                       'emergency_fae_admission', 'A2_dms_jours', 'fce_bed_days',
                       'emergency_fae_discharge', 'elective_fae_discharge', 'other_fae_discharge']
    df_prov = df_prov[df_prov['Trust_code'].astype(str).str.len() == 3]
    for col in ['total_admissions', 'A2_dms_jours', 'other_fae_discharge',
                'emergency_fae_admission']:
        df_prov[col] = pd.to_numeric(df_prov[col], errors='coerce')
    df_prov['A9_taux_transfert_pct'] = df_prov['other_fae_discharge'] / df_prov['total_admissions'] * 100
    df_prov['pct_admissions_urgentes'] = df_prov['emergency_fae_admission'] / df_prov['total_admissions'] * 100
    df_prov = df_prov.dropna(subset=['A2_dms_jours', 'A9_taux_transfert_pct'])
    print(f"✅ Hospital Providers : {len(df_prov)} trusts")

    # ── 5. AEQI ──
    aeqi_path = paths['aeqi']
    if aeqi_path.startswith('http'):
        response = requests.get(aeqi_path, timeout=120)
        df_aeqi = pd.read_csv(io.StringIO(response.content.decode('utf-8')))
    else:
        df_aeqi = pd.read_csv(aeqi_path)

    df_aeqi['ATTENDANCE_MONTH'] = pd.to_datetime(df_aeqi['ATTENDANCE_MONTH'])
    df_a4 = df_aeqi[df_aeqi['MEASURE_NAME'] == 'TOTAL_TIME_MEDIAN'].copy()
    df_a4['MEASURE_VALUE'] = pd.to_numeric(df_a4['MEASURE_VALUE'], errors='coerce')
    df_a4 = df_a4.groupby(['ORG_CODE', 'ORG_NAME'])['MEASURE_VALUE'].mean().reset_index()
    df_a4.columns = ['Trust_code', 'Trust_name_a4', 'A4_temps_attente_min']
    df_a4 = df_a4[df_a4['Trust_code'].astype(str).str.len() == 3]
    print(f"✅ AEQI : {len(df_a4)} trusts")

    # ── 6. Workforce ──
    df_org = pd.read_excel(paths['workforce'], 
                            sheet_name='3. NHSE, Org & SG - FTE', header=5)
    df_org = df_org[df_org['Organisation code'].notna()].copy()
    df_workforce = df_org[['Organisation code', 'Organisation name',
                            'HCHS Doctors', 'Nurses & health visitors']].copy()
    df_workforce.columns = ['Trust_code', 'Trust_name_workforce',
                             'B7_medecins_fte', 'B7_infirmiers_fte']
    df_workforce['B7_medecins_fte']  = pd.to_numeric(df_workforce['B7_medecins_fte'], errors='coerce')
    df_workforce['B7_infirmiers_fte'] = pd.to_numeric(df_workforce['B7_infirmiers_fte'], errors='coerce')
    df_workforce = df_workforce.dropna()
    df_workforce = df_workforce.merge(df_beds[['Trust_code', 'lits_disponibles']], 
                                       on='Trust_code', how='left')
    df_workforce['ratio_medecin_lit']       = df_workforce['B7_medecins_fte'] / df_workforce['lits_disponibles']
    df_workforce['ratio_infirmier_lit']     = df_workforce['B7_infirmiers_fte'] / df_workforce['lits_disponibles']
    df_workforce['ratio_infirmier_medecin'] = df_workforce['B7_infirmiers_fte'] / df_workforce['B7_medecins_fte']
    df_workforce = df_workforce.replace([np.inf, -np.inf], np.nan).dropna(
        subset=['ratio_medecin_lit', 'ratio_infirmier_lit', 'ratio_infirmier_medecin'])
    print(f"✅ Workforce : {len(df_workforce)} trusts")

    # ── 7. NIDC ──
    df_nidc = pd.read_excel(paths['nidc'], 
                             sheet_name='ICB, Imaging Network and Trust', header=13)
    df_nidc = df_nidc[df_nidc['Organisation Code'].notna()].copy()
    df_nidc = df_nidc[df_nidc['Organisation Code'].astype(str).str.len() == 3]
    df_nidc = df_nidc[['Organisation Code', 'Organisation Name', 'Total']].copy()
    df_nidc.columns = ['Trust_code', 'Trust_name_nidc', 'equipements_total']
    df_nidc['equipements_total'] = pd.to_numeric(df_nidc['equipements_total'], errors='coerce')
    df_nidc = df_nidc.merge(df_beds[['Trust_code', 'lits_disponibles']], 
                             on='Trust_code', how='left')
    df_nidc['D5_ratio_equipement_lit'] = df_nidc['equipements_total'] / df_nidc['lits_disponibles']
    print(f"✅ NIDC : {len(df_nidc)} trusts")

    # ── FUSION ──
    df = df_shmi[['Trust_code', 'Trust_name_shmi', 'C3_mortalite_pct', 
                   'SHMI_VALUE', 'spells_total', 'deces_observes']].copy()
    df = df.merge(df_beds[['Trust_code', 'lits_disponibles', 'C2_occupation_pct', 
                            'A8_lits_vacants_pct']], on='Trust_code', how='left')
    df = df.merge(df_cdi[['Trust_code', 'CDI_total_cases', 'C4_infections_pct']], 
                  on='Trust_code', how='left')
    df = df.merge(df_prov[['Trust_code', 'A2_dms_jours', 'A9_taux_transfert_pct',
                            'total_admissions', 'pct_admissions_urgentes']], 
                  on='Trust_code', how='left')
    df = df.merge(df_a4[['Trust_code', 'A4_temps_attente_min']], 
                  on='Trust_code', how='left')
    df = df.merge(df_workforce[['Trust_code', 'B7_medecins_fte', 'B7_infirmiers_fte',
                                 'ratio_medecin_lit', 'ratio_infirmier_lit', 
                                 'ratio_infirmier_medecin']], 
                  on='Trust_code', how='left')
    df = df.merge(df_nidc[['Trust_code', 'equipements_total', 'D5_ratio_equipement_lit']], 
                  on='Trust_code', how='left')
    
    df = df.dropna()
    df['annee'] = annee
    
    print(f"\n✅ Dataset {annee} : {len(df)} trusts × {len(df.columns)} colonnes")
    return df

print("✅ Fonction définie !")

✅ Fonction définie !

In [20]:
# ============================================
# CELLULE 12 — CHARGEMENT 2022-23 ET 2023-24
# ============================================
DATA = r'C:\Users\hp\healthsim-simulation\data'

# ── Chemins 2023-24 ──
paths_2324 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2023-24-Final.xlsx',
    'shmi'      : rf'{DATA}\SHMI data, Apr23-Mar24.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_april_2023_to_march_2024-os.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2023-24-tab.xlsx',
    'aeqi'      : 'https://files.digital.nhs.uk/23/C1A9E0/aeqi_open_data_2024_03.csv',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2024 England and Organisation.xlsx',
    'nidc'      : rf'{DATA}\National-Imaging-Data-Collection-Asset-Count-2023-24-v1.xlsx',
}

# ── Chemins 2022-23 ──
paths_2223 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2022-23-Final.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr22-Mar23.zip',
    'cdi'       : rf'{DATA}\Table-6-CDI-march-2023.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2022-23-tab_v2.xlsx',
    'aeqi'      : rf'{DATA}\aeqi_open_data_2023_03.csv',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2023 England and Organisation.xlsx',
    'nidc'      : rf'{DATA}\National-Imaging-Data-Collection-Asset-Count-2022-23-v1.xlsx',
}

# ── Chargement ──
df_2324 = charger_annee('2023-24', paths_2324)
df_2223 = charger_annee('2022-23', paths_2223)

# ── Combinaison ──
df_combined = pd.concat([df_2324, df_2223], ignore_index=True)

print(f"\n{'='*50}")
print(f"✅ Dataset combiné : {len(df_combined)} trusts × {len(df_combined.columns)} colonnes")
print(f"\nDistribution par année :")
print(df_combined['annee'].value_counts())

==================================================
Chargement année 2023-24...
==================================================
✅ Beds : 185 trusts
  Fichier SHMI trouvé : SHMI_data_at_trust_level_Apr23-Mar24_csv.csv
✅ SHMI : 119 trusts
✅ CDI : 136 trusts
✅ Hospital Providers : 150 trusts
✅ AEQI : 154 trusts
✅ Workforce : 185 trusts
✅ NIDC : 138 trusts

✅ Dataset 2023-24 : 103 trusts × 24 colonnes

==================================================
Chargement année 2022-23...
==================================================
✅ Beds : 187 trusts
  Fichier SHMI trouvé : SHMI data at trust level, Apr22-Mar23 (csv).csv
✅ SHMI : 120 trusts
✅ CDI : 135 trusts
✅ Hospital Providers : 144 trusts
✅ AEQI : 154 trusts
✅ Workforce : 187 trusts
✅ NIDC : 137 trusts

✅ Dataset 2022-23 : 103 trusts × 24 colonnes

==================================================
✅ Dataset combiné : 206 trusts × 24 colonnes

Distribution par année :
annee
2023-24    103
2022-23    103
Name: count, dtype: int64

In [21]:
# CELLULE DIAGNOSTIC — Voir le contenu du ZIP SHMI 2022-23
import zipfile

with zipfile.ZipFile(r'C:\Users\hp\healthsim-simulation\data\SHMI data files, Apr22-Mar23.zip', 'r') as z:
    print("Fichiers dans le ZIP 2022-23 :")
    for f in z.namelist():
        if '.csv' in f.lower():
            print(f"  - {f}")

Fichiers dans le ZIP 2022-23 :
  - SHMI contextual indicators/Admission method/Deaths within 30 days for elective admissions, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Admission method/Deaths within 30 days for non-elective admissions, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/COVID-19 activity/Percentage of provider spells with COVID-19 coding, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/COVID-19 activity/Provider spells compared to the pre-pandemic period, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Deprivation/Deaths split by deprivation quintile, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Deprivation/Provider spells split by deprivation quintile, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Depth of coding/Mean depth of coding for elective admissions, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Depth of coding/Mean depth of coding for non-elective admissions, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/In and outside hospital deaths/Deaths occurring in and outside hospital, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Palliative care coding/Percentage of deaths with palliative care coding, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Palliative care coding/Percentage of provider spells with palliative care coding, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Primary diagnosis coding/Provider spells with a primary diagnosis which is a symptom or sign, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Primary diagnosis coding/Provider spells with an invalid primary diagnosis code, Apr22-Mar23 (csv).csv
  - SHMI contextual indicators/Site change during spell/Percentage of provider spells with site of treatment change, Apr22-Mar23 (csv).csv
  - SHMI data/Historical trust level SHMI data, Apr22-Mar23 (csv).csv
  - SHMI data/SHMI data at site level, Apr22-Mar23 (csv).csv
  - SHMI data/SHMI data at trust level, Apr22-Mar23 (csv).csv
  - SHMI data/SHMI diagnosis group breakdown, Apr22-Mar23 (csv).csv
  - SHMI statistical model data/SHMI model fit statistics, Apr22-Mar23 (csv).csv
  - SHMI statistical model data/SHMI model predict statistics, Apr22-Mar23 (csv).csv

In [22]:
# CELLULE DIAGNOSTIC — Colonnes Hospital Providers 2022-23
df_prov_raw_2223 = pd.read_excel(
    r'C:\Users\hp\healthsim-simulation\data\hosp-epis-stat-admi-hosp-prov-2022-23-tab_v2.xlsx',
    sheet_name='Hospital Providers', header=16)

print("Colonnes disponibles :")
for col in df_prov_raw_2223.columns:
    print(f"  - '{col}'")

Colonnes disponibles :
  - 'Hospital provider code and description†'
  - 'Unnamed: 1'
  - 'Unnamed: 2'
  - 'Unnamed: 3'
  - 'Unnamed: 4'
  - 'Unnamed: 5'
  - 'Unnamed: 6'
  - 'Finished consultant episodes'
  - 'Admissions'
  - 'Male'
  - 'Female'
  - 'Gender Unknown'
  - 'Emergency'
  - 'Waiting list'
  - 'Planned'
  - 'Other Admission Method'
  - 'Mean time waited'
  - 'Median time waited'
  - 'Mean length of stay'
  - 'Median length of stay'
  - 'Mean age'
  - 'Age 0'
  - 'Age 1-4'
  - 'Age 5-9'
  - 'Age 10-14'
  - 'Age 15'
  - 'Age 16'
  - 'Age 17'
  - 'Age 18'
  - 'Age 19'
  - 'Age 20-24'
  - 'Age 25-29'
  - 'Age 30-34'
  - 'Age 35-39'
  - 'Age 40-44'
  - 'Age 45-49'
  - 'Age 50-54'
  - 'Age 55-59'
  - 'Age 60-64'
  - 'Age 65-69'
  - 'Age 70-74'
  - 'Age 75-79'
  - 'Age 80-84'
  - 'Age 85-89'
  - 'Age 90+'
  - 'Day case'
  - 'FCE bed days'
  - 'Emergency.1'
  - 'Elective'
  - 'Other'

In [23]:
# ============================================
# CELLULE 13 — CALCUL DU LABEL SUR df_combined
# ============================================
def calculer_statut(row):
    C2   = row['C2_occupation_pct']
    SHMI = row['SHMI_VALUE']
    A2   = row['A2_dms_jours']
    A4   = row['A4_temps_attente_min']
    A9   = row['A9_taux_transfert_pct']

    critique  = 0
    attention = 0

    if C2 > 92:    critique  += 1
    elif C2 > 85:  attention += 1

    if SHMI > 1.15:   critique  += 1
    elif SHMI > 1.0:  attention += 1

    if A2 > 7:     critique  += 1
    elif A2 > 4.5: attention += 1

    if A4 > 720:   critique  += 1
    elif A4 > 240: attention += 1

    if A9 > 5:    critique  += 1
    elif A9 > 2:  attention += 1

    if critique >= 2:
        return 0  # Critique
    elif critique >= 1 or attention >= 2:
        return 1  # Attention
    else:
        return 2  # Normal

df_combined['statut'] = df_combined.apply(calculer_statut, axis=1)
statut_map = {0: 'Critique', 1: 'Attention', 2: 'Normal'}
df_combined['statut_label'] = df_combined['statut'].map(statut_map)

print("✅ Labels calculés !")
print(f"\nDistribution globale :")
print(df_combined['statut_label'].value_counts())
print(f"\nEn % :")
print((df_combined['statut_label'].value_counts(normalize=True) * 100).round(1))
print(f"\nDistribution par année :")
print(df_combined.groupby(['annee', 'statut_label']).size().unstack(fill_value=0))

✅ Labels calculés !

Distribution globale :
statut_label
Attention    160
Critique      30
Normal        16
Name: count, dtype: int64

En % :
statut_label
Attention    77.7
Critique     14.6
Normal        7.8
Name: proportion, dtype: float64

Distribution par année :
statut_label  Attention  Critique  Normal
annee
2022-23              86        10       7
2023-24              74        20       9

In [24]:
# ============================================
# CELLULE 14 — SAUVEGARDE DU DATASET FINAL
# ============================================
import os

# Créer le dossier datasets
os.makedirs(r'C:\Users\hp\healthsim-simulation\data\datasets', exist_ok=True)

# Features finales — toutes calculables dans HealthSim
FEATURES = [
    'A2_dms_jours',           # calculé depuis simulation
    'A4_temps_attente_min',   # calculé par Erlang-C
    'A8_lits_vacants_pct',    # calculé depuis lits
    'A9_taux_transfert_pct',  # saisi par chef service
    'C2_occupation_pct',      # calculé depuis lits
    'C3_mortalite_pct',       # saisi par chef service
    'C4_infections_pct',      # saisi par chef service
    'ratio_medecin_lit',      # médecins / lits
    'ratio_infirmier_lit',    # infirmiers / lits
    'ratio_infirmier_medecin',# infirmiers / médecins
    'D5_ratio_equipement_lit' # équipements / lits
]

# Sauvegarder le dataset
path_dataset = r'C:\Users\hp\healthsim-simulation\data\datasets\nhs_dataset_final.csv'
df_combined.to_csv(path_dataset, index=False)

print(f"✅ Dataset sauvegardé !")
print(f"Chemin : data\\datasets\\nhs_dataset_final.csv")
print(f"Dimensions : {df_combined.shape}")
print(f"\nFeatures pour le modèle : {len(FEATURES)}")
for f in FEATURES:
    print(f"  - {f}")
print(f"\nDistribution labels :")
print(df_combined['statut_label'].value_counts())

✅ Dataset sauvegardé !
Chemin : data\datasets\nhs_dataset_final.csv
Dimensions : (206, 26)

Features pour le modèle : 11
  - A2_dms_jours
  - A4_temps_attente_min
  - A8_lits_vacants_pct
  - A9_taux_transfert_pct
  - C2_occupation_pct
  - C3_mortalite_pct
  - C4_infections_pct
  - ratio_medecin_lit
  - ratio_infirmier_lit
  - ratio_infirmier_medecin
  - D5_ratio_equipement_lit

Distribution labels :
statut_label
Attention    160
Critique      30
Normal        16
Name: count, dtype: int64

In [25]:
# Voir le dataset complet
df_combined[['Trust_code', 'Trust_name_shmi', 'annee'] + FEATURES + ['statut_label']].head(20)

,Trust_code,Trust_name_shmi,annee,A2_dms_jours,A4_temps_attente_min,A8_lits_vacants_pct,A9_taux_transfert_pct,C2_occupation_pct,C3_mortalite_pct,C4_infections_pct,ratio_medecin_lit,ratio_infirmier_lit,ratio_infirmier_medecin,D5_ratio_equipement_lit,statut_label
0,RCF,AIREDALE NHS FOUNDATION TRUST,2023-24,4.027666,220.58,13.749898,2.049486,86.250102,3.393244,0.368764,0.834860,1.778592,2.130406,0.078974,Attention
1,RTK,ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATIO...,2023-24,3.144720,222.16,13.531588,6.905407,86.468412,2.796784,0.121451,1.256611,2.226957,1.772193,0.117908,Attention
2,RF4,"BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOS...",2023-24,3.516111,309.10,5.234281,0.793557,94.765719,2.283519,0.091513,1.216217,2.135719,1.756035,0.084675,Attention
3,RFF,BARNSLEY HOSPITAL NHS FOUNDATION TRUST,2023-24,3.644835,211.12,7.592712,2.914826,92.407288,3.227711,0.153513,0.828729,2.024446,2.442832,0.081929,Attention
4,R1H,BARTS HEALTH NHS TRUST,2023-24,5.373930,231.44,5.070612,1.356528,94.929388,2.722792,0.139121,1.428163,2.430055,1.701524,0.113366,Attention
5,RC9,BEDFORDSHIRE HOSPITALS NHS FOUNDATION TRUST,2023-24,3.398034,180.34,6.502244,6.559870,93.497756,2.443274,0.094003,1.051985,1.802187,1.713130,0.084124,Critique
6,RXL,BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST,2023-24,5.374062,328.64,4.060418,1.468585,95.939582,3.868265,0.203679,0.821373,2.944157,3.584434,0.084942,Attention
7,RMC,BOLTON NHS FOUNDATION TRUST,2023-24,4.061010,210.88,10.216234,7.915453,89.783766,2.998066,0.335854,0.849720,2.469066,2.905739,0.087678,Attention
8,RAE,BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST,2023-24,3.094164,215.08,7.870717,12.946923,92.129283,2.134590,0.055837,1.127823,2.119832,1.879579,0.119065,Critique
9,RXQ,BUCKINGHAMSHIRE HEALTHCARE NHS TRUST,2023-24,3.364101,301.84,4.403357,7.593318,95.596643,2.194592,0.105993,1.391809,3.338076,2.398372,0.151675,Critique
10,RWY,CALDERDALE AND HUDDERSFIELD NHS FOUNDATION TRUST,2023-24,4.068825,192.08,11.971903,2.497152,88.028097,4.064846,0.146941,0.924119,2.122068,2.296315,0.092269,Attention
11,RGT,CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION ...,2023-24,6.444772,175.40,6.082725,0.791715,93.917275,3.564116,0.300296,1.504240,2.973822,1.976960,0.095915,Attention
12,RQM,CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATIO...,2023-24,4.010396,206.16,1.071424,1.651488,98.928576,1.779305,0.064609,1.551907,2.409237,1.552436,0.125585,Attention
13,RFS,CHESTERFIELD ROYAL HOSPITAL NHS FOUNDATION TRUST,2023-24,3.170322,210.12,7.625342,5.200045,92.374658,3.095038,0.173255,0.846639,2.037414,2.406473,0.079947,Critique
14,RJR,COUNTESS OF CHESTER HOSPITAL NHS FOUNDATION TRUST,2023-24,4.388778,230.30,11.112527,7.070516,88.887473,3.302611,0.267720,1.015472,2.305895,2.270762,0.090859,Attention
15,RXP,COUNTY DURHAM AND DARLINGTON NHS FOUNDATION TRUST,2023-24,4.358714,230.88,6.146259,1.166092,93.853741,4.086478,0.189953,0.896433,2.298372,2.563908,0.094528,Critique
16,RJ6,CROYDON HEALTH SERVICES NHS TRUST,2023-24,6.420046,155.48,7.517874,1.507085,92.482126,4.200738,0.153920,1.060413,2.265178,2.136129,0.081549,Attention
17,RP5,DONCASTER AND BASSETLAW TEACHING HOSPITALS NHS...,2023-24,3.810171,178.52,8.148279,1.283033,91.851721,3.520278,0.194084,0.932303,1.930082,2.070230,0.108698,Attention
18,RBD,DORSET COUNTY HOSPITAL NHS FOUNDATION TRUST,2023-24,3.936158,102.24,10.904359,0.963978,89.095641,4.060198,0.285311,1.032636,2.207592,2.137821,0.081671,Attention
19,RWH,EAST AND NORTH HERTFORDSHIRE NHS TRUST,2023-24,4.226275,174.72,12.342844,1.227133,87.657156,3.744327,0.270424,1.450424,2.514385,1.733551,0.105276,Normal

In [26]:
# Voir TOUT le dataset
pd.set_option('display.max_rows', 206)
df_combined[['Trust_code', 'Trust_name_shmi', 'annee'] + FEATURES + ['statut_label']]

,Trust_code,Trust_name_shmi,annee,A2_dms_jours,A4_temps_attente_min,A8_lits_vacants_pct,A9_taux_transfert_pct,C2_occupation_pct,C3_mortalite_pct,C4_infections_pct,ratio_medecin_lit,ratio_infirmier_lit,ratio_infirmier_medecin,D5_ratio_equipement_lit,statut_label
0,RCF,AIREDALE NHS FOUNDATION TRUST,2023-24,4.027666,220.580000,13.749898,2.049486,86.250102,3.393244,0.368764,0.834860,1.778592,2.130406,0.078974,Attention
1,RTK,ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATIO...,2023-24,3.144720,222.160000,13.531588,6.905407,86.468412,2.796784,0.121451,1.256611,2.226957,1.772193,0.117908,Attention
2,RF4,"BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOS...",2023-24,3.516111,309.100000,5.234281,0.793557,94.765719,2.283519,0.091513,1.216217,2.135719,1.756035,0.084675,Attention
3,RFF,BARNSLEY HOSPITAL NHS FOUNDATION TRUST,2023-24,3.644835,211.120000,7.592712,2.914826,92.407288,3.227711,0.153513,0.828729,2.024446,2.442832,0.081929,Attention
4,R1H,BARTS HEALTH NHS TRUST,2023-24,5.373930,231.440000,5.070612,1.356528,94.929388,2.722792,0.139121,1.428163,2.430055,1.701524,0.113366,Attention
5,RC9,BEDFORDSHIRE HOSPITALS NHS FOUNDATION TRUST,2023-24,3.398034,180.340000,6.502244,6.559870,93.497756,2.443274,0.094003,1.051985,1.802187,1.713130,0.084124,Critique
6,RXL,BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST,2023-24,5.374062,328.640000,4.060418,1.468585,95.939582,3.868265,0.203679,0.821373,2.944157,3.584434,0.084942,Attention
7,RMC,BOLTON NHS FOUNDATION TRUST,2023-24,4.061010,210.880000,10.216234,7.915453,89.783766,2.998066,0.335854,0.849720,2.469066,2.905739,0.087678,Attention
8,RAE,BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST,2023-24,3.094164,215.080000,7.870717,12.946923,92.129283,2.134590,0.055837,1.127823,2.119832,1.879579,0.119065,Critique
9,RXQ,BUCKINGHAMSHIRE HEALTHCARE NHS TRUST,2023-24,3.364101,301.840000,4.403357,7.593318,95.596643,2.194592,0.105993,1.391809,3.338076,2.398372,0.151675,Critique
10,RWY,CALDERDALE AND HUDDERSFIELD NHS FOUNDATION TRUST,2023-24,4.068825,192.080000,11.971903,2.497152,88.028097,4.064846,0.146941,0.924119,2.122068,2.296315,0.092269,Attention
11,RGT,CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION ...,2023-24,6.444772,175.400000,6.082725,0.791715,93.917275,3.564116,0.300296,1.504240,2.973822,1.976960,0.095915,Attention
12,RQM,CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATIO...,2023-24,4.010396,206.160000,1.071424,1.651488,98.928576,1.779305,0.064609,1.551907,2.409237,1.552436,0.125585,Attention
13,RFS,CHESTERFIELD ROYAL HOSPITAL NHS FOUNDATION TRUST,2023-24,3.170322,210.120000,7.625342,5.200045,92.374658,3.095038,0.173255,0.846639,2.037414,2.406473,0.079947,Critique
14,RJR,COUNTESS OF CHESTER HOSPITAL NHS FOUNDATION TRUST,2023-24,4.388778,230.300000,11.112527,7.070516,88.887473,3.302611,0.267720,1.015472,2.305895,2.270762,0.090859,Attention
15,RXP,COUNTY DURHAM AND DARLINGTON NHS FOUNDATION TRUST,2023-24,4.358714,230.880000,6.146259,1.166092,93.853741,4.086478,0.189953,0.896433,2.298372,2.563908,0.094528,Critique
16,RJ6,CROYDON HEALTH SERVICES NHS TRUST,2023-24,6.420046,155.480000,7.517874,1.507085,92.482126,4.200738,0.153920,1.060413,2.265178,2.136129,0.081549,Attention
17,RP5,DONCASTER AND BASSETLAW TEACHING HOSPITALS NHS...,2023-24,3.810171,178.520000,8.148279,1.283033,91.851721,3.520278,0.194084,0.932303,1.930082,2.070230,0.108698,Attention
18,RBD,DORSET COUNTY HOSPITAL NHS FOUNDATION TRUST,2023-24,3.936158,102.240000,10.904359,0.963978,89.095641,4.060198,0.285311,1.032636,2.207592,2.137821,0.081671,Attention
19,RWH,EAST AND NORTH HERTFORDSHIRE NHS TRUST,2023-24,4.226275,174.720000,12.342844,1.227133,87.657156,3.744327,0.270424,1.450424,2.514385,1.733551,0.105276,Normal
20,RJN,EAST CHESHIRE NHS TRUST,2023-24,6.276542,230.240000,8.210137,0.851950,91.789863,5.408766,0.124339,0.824314,1.995178,2.420409,0.096093,Attention
21,RVV,EAST KENT HOSPITALS UNIVERSITY NHS FOUNDATION ...,2023-24,4.714139,158.880000,6.449363,1.110117,93.550637,3.801368,0.293457,1.064094,2.425757,2.279645,0.105190,Attention
22,RXR,EAST LANCASHIRE HOSPITALS NHS TRUST,2023-24,5.911377,144.380000,5.976139,1.889254,94.023861,4.690701,0.340025,0.918856,2.465071,2.682760,0.081599,Critique
23,RDE,EAST SUFFOLK AND NORTH ESSEX NHS FOUNDATION TRUST,2023-24,4.405638,167.400000,5.209543,1.189052,94.790457,4.053809,0.203823,0.962738,2.259517,2.346971,0.071004,Attention
24,RXC,EAST SUSSEX HEALTHCARE NHS TRUST,2023-24,4.668385,201.580000,9.734513,1.095523,90.265487,4.186527,0.182714,0.920500,2.489474,2.704480,0.091964,Attention
25,RDU,FRIMLEY HEALTH NHS FOUNDATION TRUST,2023-24,5.873092,266.780000,7.818097,3.582473,92.181903,3.866271,0.169318,0.901923,1.994643,2.211544,0.125108,Attention
26,RLT,GEORGE ELIOT HOSPITAL NHS TRUST,2023-24,4.300708,173.840000,0.826781,1.115486,99.173219,3.608325,0.185657,0.870974,1.699596,1.951374,0.071303,Attention
27,RTE,GLOUCESTERSHIRE HOSPITALS NHS FOUNDATION TRUST,2023-24,4.303186,205.680000,6.181045,5.577677,93.818955,2.852623,0.202699,1.096286,2.311177,2.108188,0.115464,Critique
28,RN3,GREAT WESTERN HOSPITALS NHS FOUNDATION TRUST,2023-24,3.836814,194.840000,5.665340,4.256656,94.334660,2.947033,0.180008,1.084405,2.475894,2.283183,0.077045,Attention
29,RCD,HARROGATE AND DISTRICT NHS FOUNDATION TRUST,2023-24,3.709291,139.380000,8.974494,0.774780,91.025506,3.612619,0.176391,1.253288,5.055686,4.033939,0.146461,Normal
30,RQX,HOMERTON HEALTHCARE NHS FOUNDATION TRUST,2023-24,3.001081,237.360000,14.713870,13.464226,85.286130,1.260902,0.088263,1.670100,3.364511,2.014557,0.122076,Attention
31,RWA,HULL UNIVERSITY TEACHING HOSPITALS NHS TRUST,2023-24,4.697842,266.800000,11.021997,2.263916,88.978003,3.973136,0.114002,1.029574,1.926548,1.871210,0.100724,Attention
32,RYJ,IMPERIAL COLLEGE HEALTHCARE NHS TRUST,2023-24,4.203913,181.660000,11.655007,7.531674,88.344993,1.927578,0.119326,1.884782,3.451169,1.831071,0.120706,Attention
33,RGP,JAMES PAGET UNIVERSITY HOSPITALS NHS FOUNDATIO...,2023-24,5.237157,213.740000,12.700574,0.983342,87.299426,4.876274,0.142649,0.925919,2.170554,2.344216,0.081858,Attention
34,RNQ,KETTERING GENERAL HOSPITAL NHS FOUNDATION TRUST,2023-24,4.360995,227.880000,4.839959,4.437224,95.160041,3.585496,0.187860,0.889138,2.005593,2.255659,0.078859,Attention
35,RJZ,KING'S COLLEGE HOSPITAL NHS FOUNDATION TRUST,2023-24,5.767131,206.860000,7.931198,7.220217,92.068802,3.086008,0.186906,1.726158,3.036611,1.759173,0.121672,Critique
36,RAX,KINGSTON HOSPITAL NHS FOUNDATION TRUST,2023-24,3.390205,222.740000,10.986648,13.530258,89.013352,2.086411,0.099705,1.266308,2.327699,1.838178,0.122581,Attention
37,RXN,LANCASHIRE TEACHING HOSPITALS NHS FOUNDATION T...,2023-24,4.279451,201.360000,6.510222,5.579837,93.489778,2.836314,0.346281,1.080046,2.538317,2.350194,0.107715,Critique
38,RR8,LEEDS TEACHING HOSPITALS NHS TRUST,2023-24,6.726851,225.760000,5.701106,1.870434,94.298894,4.018432,0.259637,1.298195,2.282042,1.757857,0.089576,Attention
39,RJ2,LEWISHAM AND GREENWICH NHS TRUST,2023-24,4.477368,227.180000,6.293917,6.595915,93.706083,2.871940,0.067090,0.952358,2.028659,2.130143,0.071782,Critique
40,REM,LIVERPOOL UNIVERSITY HOSPITALS NHS FOUNDATION ...,2023-24,5.702484,239.480000,7.336008,0.013649,92.663992,3.958162,0.247129,1.038665,2.343606,2.256363,0.087684,Attention
41,R1K,LONDON NORTH WEST UNIVERSITY HEALTHCARE NHS TRUST,2023-24,3.878259,251.800000,6.314272,2.760048,93.685728,2.543893,0.100057,1.383243,2.435734,1.760886,0.096332,Attention
42,RWF,MAIDSTONE AND TUNBRIDGE WELLS NHS TRUST,2023-24,2.740721,110.104167,13.852938,1.211786,86.147062,2.470806,0.183431,1.230888,2.292842,1.862754,0.103265,Normal
43,RPA,MEDWAY NHS FOUNDATION TRUST,2023-24,4.782567,199.000000,15.889486,1.621385,84.110514,3.613429,0.140364,1.193290,2.119081,1.775831,0.082885,Attention
44,RBN,MERSEY AND WEST LANCASHIRE TEACHING HOSPITALS ...,2023-24,3.671136,183.200000,6.183153,4.386644,93.816847,3.096241,0.178330,0.962282,1.984982,2.062787,0.052113,Attention
45,RAJ,MID AND SOUTH ESSEX NHS FOUNDATION TRUST,2023-24,4.204157,219.080000,6.352277,5.165835,93.647723,3.459102,0.240609,1.131853,2.233100,1.972959,0.090430,Critique
46,RBT,MID CHESHIRE HOSPITALS NHS FOUNDATION TRUST,2023-24,3.534684,161.640000,11.345614,7.345175,88.654386,2.866414,0.104561,0.849522,2.471369,2.909128,0.098064,Attention
47,RD8,MILTON KEYNES UNIVERSITY HOSPITAL NHS FOUNDATI...,2023-24,5.082615,217.340000,7.991381,1.967957,92.008619,3.555210,0.166083,0.883853,1.751172,1.981292,0.117650,Attention
48,RM1,NORFOLK AND NORWICH UNIVERSITY HOSPITALS NHS F...,2023-24,5.159172,212.900000,5.384821,4.719550,94.615179,4.799737,0.231123,1.153316,2.086946,1.809518,0.079609,Critique
49,RNN,NORTH CUMBRIA INTEGRATED CARE NHS FOUNDATION T...,2023-24,5.624817,176.980000,9.546651,1.090028,90.453349,4.641579,0.273289,0.924964,2.660346,2.876162,0.092592,Attention
50,RAP,NORTH MIDDLESEX UNIVERSITY HOSPITAL NHS TRUST,2023-24,7.059913,212.740000,3.075406,1.149425,96.924594,4.177719,0.132626,1.385388,2.958297,2.135356,0.100654,Critique
51,RVW,NORTH TEES AND HARTLEPOOL NHS FOUNDATION TRUST,2023-24,3.263449,81.400000,11.495054,1.371935,88.504946,3.284239,0.177755,0.870916,2.297419,2.637935,0.076817,Normal
52,RGN,NORTH WEST ANGLIA NHS FOUNDATION TRUST,2023-24,4.316513,214.280000,16.415415,1.398575,83.584585,3.544556,0.237547,0.852983,1.821994,2.136027,0.072873,Normal
53,RNS,NORTHAMPTON GENERAL HOSPITAL NHS TRUST,2023-24,3.334773,173.800000,15.215311,7.373610,84.784689,2.663815,0.206105,0.944012,1.827270,1.935642,0.067872,Attention
54,RM3,NORTHERN CARE ALLIANCE NHS FOUNDATION TRUST,2023-24,4.457058,211.440000,16.865395,1.352468,83.134605,3.623477,0.241300,1.227985,3.259895,2.654669,0.095906,Normal
55,RTF,NORTHUMBRIA HEALTHCARE NHS FOUNDATION TRUST,2023-24,2.796159,90.960000,13.161515,7.233305,86.838485,3.051497,0.136048,0.827057,2.346782,2.837509,0.101016,Attention
56,RX1,NOTTINGHAM UNIVERSITY HOSPITALS NHS TRUST,2023-24,4.346287,254.720000,11.879006,5.646676,88.120994,3.116709,0.152828,1.259584,2.670165,2.119878,0.072568,Attention
57,RTH,OXFORD UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,2023-24,3.660104,225.480000,6.230517,1.618084,93.769483,2.414330,0.154206,1.854557,3.519653,1.897840,0.138478,Attention
58,RHU,PORTSMOUTH HOSPITALS UNIVERSITY NATIONAL HEALT...,2023-24,4.558471,206.380000,4.946237,1.037707,95.053763,3.443475,0.191721,1.016129,2.116800,2.083200,0.076058,Attention
59,RHW,ROYAL BERKSHIRE NHS FOUNDATION TRUST,2023-24,3.469070,166.240000,4.734229,7.586764,95.265771,3.258224,0.169585,1.227698,2.612935,2.128320,0.105185,Critique
60,RH8,ROYAL DEVON UNIVERSITY HEALTHCARE NHS FOUNDATI...,2023-24,4.120633,221.280000,11.600372,1.398343,88.399628,3.516975,0.153486,1.065404,2.479915,2.327676,0.083847,Normal
61,RAL,ROYAL FREE LONDON NHS FOUNDATION TRUST,2023-24,4.291176,208.840000,23.312295,10.506515,76.687705,2.394116,0.147108,1.489369,2.524270,1.694859,0.128833,Attention
62,RD1,ROYAL UNITED HOSPITALS BATH NHS FOUNDATION TRUST,2023-24,3.722486,226.020000,6.197779,1.612986,93.802221,3.158065,0.243922,1.197779,2.674680,2.233032,0.098745,Attention
63,RNZ,SALISBURY NHS FOUNDATION TRUST,2023-24,5.117211,224.580000,8.356127,1.180193,91.643873,2.981442,0.149072,0.944576,2.076338,2.198169,0.112008,Attention
64,RHQ,SHEFFIELD TEACHING HOSPITALS NHS FOUNDATION TRUST,2023-24,4.518248,174.340000,11.914969,4.495992,88.085031,2.913682,0.161871,1.074365,2.530089,2.354963,0.076532,Attention
65,RK5,SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST,2023-24,4.034590,179.920000,8.438722,7.090935,91.561278,3.549176,0.171938,0.936052,1.914470,2.045260,0.215436,Attention
66,RH5,SOMERSET NHS FOUNDATION TRUST,2023-24,5.768417,139.640000,10.092977,3.250224,89.907023,3.965696,0.188553,0.780499,2.132494,2.732217,0.070218,Attention
67,RTR,SOUTH TEES HOSPITALS NHS FOUNDATION TRUST,2023-24,3.639341,167.800000,11.276928,9.879878,88.723072,2.795677,0.199909,1.130646,2.721823,2.407316,0.089200,Attention
68,R0B,SOUTH TYNESIDE AND SUNDERLAND NHS FOUNDATION T...,2023-24,4.735155,159.320000,14.233384,0.993804,85.766616,4.014328,0.137105,0.826302,2.486961,3.009747,0.052495,Attention
69,RJC,SOUTH WARWICKSHIRE UNIVERSITY NHS FOUNDATION T...,2023-24,3.933183,195.560000,12.039149,1.218915,87.960851,3.164908,0.131038,0.932040,2.965952,3.182216,0.078586,Attention
70,RJ7,ST GEORGE'S UNIVERSITY HOSPITALS NHS FOUNDATIO...,2023-24,5.416768,289.760000,4.852700,5.039933,95.147300,2.610261,0.129013,1.637089,2.746551,1.677704,0.169149,Critique
71,RWJ,STOCKPORT NHS FOUNDATION TRUST,2023-24,4.487352,222.520000,9.400699,1.642083,90.599301,3.246035,0.250830,0.884478,2.288253,2.587123,0.068298,Normal
72,RTP,SURREY AND SUSSEX HEALTHCARE NHS TRUST,2023-24,4.565320,211.000000,14.729852,1.317638,85.270148,3.435970,0.159349,0.782064,1.607522,2.055485,0.069266,Attention
73,RMP,TAMESIDE AND GLOSSOP INTEGRATED CARE NHS FOUND...,2023-24,3.503412,187.980000,9.723831,1.144908,90.276169,3.340415,0.207743,0.844322,2.310635,2.736675,0.082225,Attention
74,RNA,THE DUDLEY GROUP NHS FOUNDATION TRUST,2023-24,2.901009,191.180000,5.742413,10.480717,94.257587,2.847896,0.135334,0.991202,2.378370,2.399481,0.133580,Critique
75,RAS,THE HILLINGDON HOSPITALS NHS FOUNDATION TRUST,2023-24,3.921880,209.760000,24.861837,8.074356,75.138163,2.133086,0.097380,0.821970,1.525926,1.856426,0.096195,Attention
76,RTD,THE NEWCASTLE UPON TYNE HOSPITALS NHS FOUNDATI...,2023-24,4.659917,147.640000,14.708783,0.697615,85.291217,2.548822,0.176951,1.221106,2.834994,2.321661,0.081413,Attention
77,RQW,THE PRINCESS ALEXANDRA HOSPITAL NHS TRUST,2023-24,4.203709,229.120000,14.913343,1.802700,85.086657,3.582234,0.186373,1.177165,2.010802,1.708173,0.104208,Attention
78,RCX,"THE QUEEN ELIZABETH HOSPITAL, KING'S LYNN, NHS...",2023-24,4.319489,219.440000,4.293516,5.789573,95.706484,3.567156,0.250136,0.829063,1.561289,1.883197,0.065206,Critique
79,RFR,THE ROTHERHAM NHS FOUNDATION TRUST,2023-24,3.249019,241.440000,9.421539,0.946143,90.578461,2.971171,0.164738,0.863560,2.262487,2.619955,0.091707,Attention
80,RL4,THE ROYAL WOLVERHAMPTON NHS TRUST,2023-24,3.074858,151.800000,8.863330,4.456411,91.136670,2.572587,0.132358,1.318439,3.083860,2.339023,0.064219,Attention
81,RXW,THE SHREWSBURY AND TELFORD HOSPITAL NHS TRUST,2023-24,4.155193,227.680000,5.265396,0.991410,94.734604,3.763181,0.194362,0.987632,2.075917,2.101914,0.068934,Attention
82,RA9,TORBAY AND SOUTH DEVON NHS FOUNDATION TRUST,2023-24,4.347524,199.480000,6.237155,0.082435,93.762845,4.327095,0.262248,1.499571,3.351146,2.234736,0.127284,Attention
83,RWD,UNITED LINCOLNSHIRE HOSPITALS NHS TRUST,2023-24,4.618282,281.860000,18.060869,1.337979,81.939131,4.314483,0.140907,0.961733,1.871296,1.945754,0.103575,Attention
84,RRV,UNIVERSITY COLLEGE LONDON HOSPITALS NHS FOUNDA...,2023-24,5.073606,190.360000,23.945469,4.899460,76.054531,1.774319,0.154086,2.136128,3.647143,1.707362,0.136794,Attention
85,RHM,UNIVERSITY HOSPITAL SOUTHAMPTON NHS FOUNDATION...,2023-24,5.033945,232.360000,8.103358,0.880317,91.896642,3.041126,0.165975,1.465523,2.922921,1.994456,0.078380,Attention
86,RA7,UNIVERSITY HOSPITALS BRISTOL AND WESTON NHS FO...,2023-24,3.646551,198.120000,4.851662,4.590164,95.148338,2.265298,0.171279,1.529506,3.117639,2.038330,0.122109,Attention
87,RKB,UNIVERSITY HOSPITALS COVENTRY AND WARWICKSHIRE...,2023-24,4.274256,138.400000,6.798482,5.148521,93.201518,2.896038,0.135624,1.066483,2.191310,2.054707,0.080157,Critique
88,R0D,UNIVERSITY HOSPITALS DORSET NHS FOUNDATION TRUST,2023-24,3.975235,241.340000,10.172900,1.328951,89.827100,3.757402,0.187870,0.955966,1.927398,2.016179,0.087269,Attention
89,RTG,UNIVERSITY HOSPITALS OF DERBY AND BURTON NHS F...,2023-24,4.255169,194.680000,9.932833,4.144640,90.067167,3.358361,0.202685,0.999138,2.152931,2.154788,0.107343,Attention
90,RWE,UNIVERSITY HOSPITALS OF LEICESTER NHS TRUST,2023-24,3.741601,214.720000,7.351166,6.716365,92.648834,2.486899,0.187805,1.251958,2.356713,1.882421,0.120906,Critique
91,RTX,UNIVERSITY HOSPITALS OF MORECAMBE BAY NHS FOUN...,2023-24,4.031474,166.500000,12.900956,0.789243,87.099044,3.542857,0.253187,0.924151,2.837935,3.070857,0.116409,Normal
92,RJE,UNIVERSITY HOSPITALS OF NORTH MIDLANDS NHS TRUST,2023-24,3.403469,186.120000,12.213544,6.410466,87.786456,2.882737,0.173772,1.018023,2.071201,2.034533,0.090909,Attention
93,RK9,UNIVERSITY HOSPITALS PLYMOUTH NHS TRUST,2023-24,5.211847,277.440000,11.573959,1.177643,88.426041,3.187148,0.268187,1.077465,2.101688,1.950586,0.104548,Attention
94,RBK,WALSALL HEALTHCARE NHS TRUST,2023-24,2.825253,192.360000,12.317522,10.844989,87.682478,2.234206,0.190503,0.937191,2.434231,2.597370,0.075760,Attention
95,RWW,WARRINGTON AND HALTON TEACHING HOSPITALS NHS F...,2023-24,5.594986,207.300000,9.143575,1.384840,90.856425,3.981623,0.236670,0.704223,1.655640,2.351016,0.095275,Attention
96,RWG,WEST HERTFORDSHIRE TEACHING HOSPITALS NHS TRUST,2023-24,4.012614,203.120000,14.305204,1.568085,85.694796,3.462470,0.167877,0.991233,2.123223,2.142003,0.117326,Attention
97,RGR,WEST SUFFOLK NHS FOUNDATION TRUST,2023-24,4.652740,209.460000,13.892251,1.322124,86.107749,3.645332,0.286333,1.024055,2.227811,2.175479,0.088892,Attention
98,RKE,WHITTINGTON HEALTH NHS TRUST,2023-24,4.998919,214.800000,13.183493,1.908990,86.816507,2.800092,0.188203,1.643610,3.295948,2.005310,0.166163,Attention
99,RBL,WIRRAL UNIVERSITY TEACHING HOSPITAL NHS FOUNDA...,2023-24,4.642496,243.240000,8.548256,4.810890,91.451744,3.284758,0.256794,0.850945,1.878353,2.207374,0.065158,Attention
100,RRF,"WRIGHTINGTON, WIGAN AND LEIGH NHS FOUNDATION T...",2023-24,3.894523,171.480000,10.366062,0.922653,89.633938,3.689093,0.208978,1.106381,3.133607,2.832304,0.142843,Attention
101,RLQ,WYE VALLEY NHS TRUST,2023-24,4.134913,239.040000,2.436393,1.242642,97.563607,3.818413,0.229105,1.274238,3.004119,2.357580,0.136194,Attention
102,RCB,YORK AND SCARBOROUGH TEACHING HOSPITALS NHS FO...,2023-24,3.830812,219.620000,7.823255,5.262274,92.176745,3.390277,0.229885,1.042856,2.325998,2.230412,0.098784,Critique
103,RCF,AIREDALE NHS FOUNDATION TRUST,2022-23,3.869658,198.320000,14.549610,2.826005,85.450390,2.920879,0.243942,0.786151,1.725605,2.195003,0.080801,Attention
104,RTK,ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATIO...,2022-23,3.192625,212.400000,9.769703,5.209431,90.230297,2.838899,0.093192,1.355098,2.285899,1.686887,0.129152,Attention
105,RF4,"BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOS...",2022-23,4.459788,344.760000,2.991606,1.108033,97.008394,3.063577,0.104344,1.103681,1.866050,1.690751,0.084257,Attention
106,RFF,BARNSLEY HOSPITAL NHS FOUNDATION TRUST,2022-23,3.674760,209.720000,9.748020,3.837381,90.251980,3.264095,0.145071,0.897600,2.107085,2.347466,0.090713,Attention
107,R1H,BARTS HEALTH NHS TRUST,2022-23,5.474242,223.120000,8.920613,1.577311,91.079387,2.632680,0.133936,1.386717,2.324662,1.676378,0.119048,Attention
108,RC9,BEDFORDSHIRE HOSPITALS NHS FOUNDATION TRUST,2022-23,3.660517,215.720000,6.502244,6.892992,93.497756,2.660326,0.105471,0.992501,1.724732,1.737764,0.084957,Critique
109,RXL,BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST,2022-23,5.727093,297.360000,2.697587,1.299519,97.302413,3.744514,0.300682,0.816265,2.795853,3.425180,0.080624,Attention
110,RMC,BOLTON NHS FOUNDATION TRUST,2022-23,4.146688,193.600000,15.213786,7.482909,84.786214,2.741248,0.366735,0.794228,2.356027,2.966436,0.071133,Attention
111,RAE,BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST,2022-23,3.120851,220.600000,14.250677,12.223245,85.749323,2.081107,0.074191,1.093615,1.879181,1.718321,0.107501,Attention
112,RXQ,BUCKINGHAMSHIRE HEALTHCARE NHS TRUST,2022-23,3.963175,249.400000,3.653911,5.414855,96.346089,2.543759,0.163586,1.125813,2.578809,2.290619,0.055891,Critique
113,RWY,CALDERDALE AND HUDDERSFIELD NHS FOUNDATION TRUST,2022-23,3.886187,178.900000,12.431246,2.460247,87.568754,3.570245,0.173956,0.884758,2.093983,2.366729,0.093325,Attention
114,RGT,CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION ...,2022-23,6.499299,170.720000,2.349115,0.974252,97.650885,3.489613,0.282453,1.541255,3.009222,1.952450,0.084453,Attention

In [27]:
# ============================================
# CELLULE — NETTOYAGE ET RENOMMAGE
# ============================================

# Supprimer spells_total et Pct_Admissions_Urgentes
df_combined = df_combined.drop(columns=['spells_total', 'pct_admissions_urgentes'])

# Renommer toutes les colonnes
df_combined = df_combined.rename(columns={
    'Trust_code'              : 'Code_Hopital',
    'Trust_name_shmi'         : 'Nom_Hopital',
    'C3_mortalite_pct'        : 'Taux_Mortalite',
    'SHMI_VALUE'              : 'SHMI',
    'deces_observes'          : 'Nombre_Deces',
    'lits_disponibles'        : 'Lits_Disponibles',
    'C2_occupation_pct'       : 'Taux_Occupation',
    'A8_lits_vacants_pct'     : 'Taux_Lits_Vacants',
    'CDI_total_cases'         : 'Total_Infections_CDI',
    'C4_infections_pct'       : 'Taux_Infections',
    'A2_dms_jours'            : 'Duree_Moyenne_Sejour_Jours',
    'A9_taux_transfert_pct'   : 'Taux_Transfert',
    'total_admissions'        : 'Total_Admissions',
    'A4_temps_attente_min'    : 'Temps_Attente_Min',
    'B7_medecins_fte'         : 'Nombre_Medecins',
    'B7_infirmiers_fte'       : 'Nombre_Infirmiers',
    'ratio_medecin_lit'       : 'Ratio_Medecin_Lit',
    'ratio_infirmier_lit'     : 'Ratio_Infirmier_Lit',
    'ratio_infirmier_medecin' : 'Ratio_Infirmier_Medecin',
    'equipements_total'       : 'Total_Equipements',
    'D5_ratio_equipement_lit' : 'Ratio_Equipement_Lit',
    'annee'                   : 'Annee',
    'statut'                  : 'Statut',
    'statut_label'            : 'Statut_Label'
})

# Recalculer C3 avec Total_Admissions
df_combined['Taux_Mortalite'] = (
    df_combined['Nombre_Deces'] /
    df_combined['Total_Admissions'] * 100
)

# Recalculer C4 avec Total_Admissions
df_combined['Taux_Infections'] = (
    df_combined['Total_Infections_CDI'] /
    df_combined['Total_Admissions'] * 100
)

# Mettre à jour FEATURES
FEATURES = [
    'Duree_Moyenne_Sejour_Jours',
    'Temps_Attente_Min',
    'Taux_Lits_Vacants',
    'Taux_Transfert',
    'Taux_Occupation',
    'Taux_Mortalite',
    'Taux_Infections',
    'Ratio_Medecin_Lit',
    'Ratio_Infirmier_Lit',
    'Ratio_Infirmier_Medecin',
    'Ratio_Equipement_Lit'
]

# Sauvegarder
path_dataset = r'C:\Users\hp\healthsim-simulation\data\datasets\nhs_dataset_final.csv'
df_combined.to_csv(path_dataset, index=False)

print("✅ Dataset nettoyé et sauvegardé !")
print(f"\nColonnes finales :")
for col in df_combined.columns:
    print(f"  - {col}")
print(f"\nDimensions : {df_combined.shape}")

✅ Dataset nettoyé et sauvegardé !

Colonnes finales :
  - Code_Hopital
  - Nom_Hopital
  - Taux_Mortalite
  - SHMI
  - Nombre_Deces
  - Lits_Disponibles
  - Taux_Occupation
  - Taux_Lits_Vacants
  - Total_Infections_CDI
  - Taux_Infections
  - Duree_Moyenne_Sejour_Jours
  - Taux_Transfert
  - Total_Admissions
  - Temps_Attente_Min
  - Nombre_Medecins
  - Nombre_Infirmiers
  - Ratio_Medecin_Lit
  - Ratio_Infirmier_Lit
  - Ratio_Infirmier_Medecin
  - Total_Equipements
  - Ratio_Equipement_Lit
  - Annee
  - Statut
  - Statut_Label

Dimensions : (206, 24)

In [28]:
# ============================================
# CELLULE — AJOUT COLONNES STATUT PAR KPI
# ============================================

def statut_kpi(valeur, seuil_critique, seuil_attention):
    if valeur > seuil_critique:
        return 'Critique'
    elif valeur > seuil_attention:
        return 'Attention'
    else:
        return 'Normal'

# Statut de chaque KPI
df_combined['Statut_C2'] = df_combined['Taux_Occupation'].apply(
    lambda x: statut_kpi(x, 92, 85))

df_combined['Statut_SHMI'] = df_combined['SHMI'].apply(
    lambda x: statut_kpi(x, 1.15, 1.0))

df_combined['Statut_A2'] = df_combined['Duree_Moyenne_Sejour_Jours'].apply(
    lambda x: statut_kpi(x, 7, 4.5))

df_combined['Statut_A4'] = df_combined['Temps_Attente_Min'].apply(
    lambda x: statut_kpi(x, 720, 240))

df_combined['Statut_A9'] = df_combined['Taux_Transfert'].apply(
    lambda x: statut_kpi(x, 5, 2))

# Sauvegarder
df_combined.to_csv(path_dataset, index=False)

print("✅ Colonnes statut par KPI ajoutées !")
print(f"\nAperçu :")
print(df_combined[['Nom_Hopital', 'Statut_C2', 'Statut_SHMI', 
                    'Statut_A2', 'Statut_A4', 'Statut_A9', 
                    'Statut_Label']].head(10).to_string())

# Sauvegarder avec les nouvelles colonnes
df_combined.to_csv(path_dataset, index=False)
print("✅ Dataset sauvegardé avec colonnes statut KPI !")
print(f"Chemin : {path_dataset}")
print(f"Dimensions : {df_combined.shape}")

✅ Colonnes statut par KPI ajoutées !

Aperçu :
                                                      Nom_Hopital  Statut_C2 Statut_SHMI  Statut_A2  Statut_A4  Statut_A9 Statut_Label
0                                   AIREDALE NHS FOUNDATION TRUST  Attention      Normal     Normal     Normal  Attention    Attention
1           ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATION TRUST  Attention      Normal     Normal     Normal   Critique    Attention
2  BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOSPITALS NHS TRUST   Critique      Normal     Normal  Attention     Normal    Attention
3                          BARNSLEY HOSPITAL NHS FOUNDATION TRUST   Critique      Normal     Normal     Normal  Attention    Attention
4                                          BARTS HEALTH NHS TRUST   Critique      Normal  Attention     Normal     Normal    Attention
5                     BEDFORDSHIRE HOSPITALS NHS FOUNDATION TRUST   Critique      Normal     Normal     Normal   Critique     Critique
6               BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST   Critique   Attention  Attention  Attention     Normal    Attention
7                                     BOLTON NHS FOUNDATION TRUST  Attention   Attention     Normal     Normal   Critique    Attention
8                BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST   Critique    Critique     Normal     Normal   Critique     Critique
9                            BUCKINGHAMSHIRE HEALTHCARE NHS TRUST   Critique      Normal     Normal  Attention   Critique     Critique
✅ Dataset sauvegardé avec colonnes statut KPI !
Chemin : C:\Users\hp\healthsim-simulation\data\datasets\nhs_dataset_final.csv
Dimensions : (206, 29)

In [29]:
# Voir tout le dataset
pd.set_option('display.max_rows', 206)
pd.set_option('display.max_columns', 30)
df_combined

,Code_Hopital,Nom_Hopital,Taux_Mortalite,SHMI,Nombre_Deces,Lits_Disponibles,Taux_Occupation,Taux_Lits_Vacants,Total_Infections_CDI,Taux_Infections,Duree_Moyenne_Sejour_Jours,Taux_Transfert,Total_Admissions,Temps_Attente_Min,Nombre_Medecins,Nombre_Infirmiers,Ratio_Medecin_Lit,Ratio_Infirmier_Lit,Ratio_Infirmier_Medecin,Total_Equipements,Ratio_Equipement_Lit,Annee,Statut,Statut_Label,Statut_C2,Statut_SHMI,Statut_A2,Statut_A4,Statut_A9
0,RCF,AIREDALE NHS FOUNDATION TRUST,1.632136,0.9745,1095.0,405.197802,86.250102,13.749898,119.0,0.177374,4.027666,2.049486,67090.0,220.580000,338.28359,720.68144,0.834860,1.778592,2.130406,32.0,0.078974,2023-24,1,Attention,Attention,Normal,Normal,Normal,Attention
1,RTK,ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATIO...,1.526753,0.9874,1635.0,525.835165,86.468412,13.531588,71.0,0.066299,3.144720,6.905407,107090.0,222.160000,660.77034,1171.01243,1.256611,2.226957,1.772193,62.0,0.117908,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
2,RF4,"BARKING, HAVERING AND REDBRIDGE UNIVERSITY HOS...",1.566386,0.8984,2645.0,1027.461538,94.765719,5.234281,106.0,0.062774,3.516111,0.793557,168860.0,309.100000,1249.61597,2194.36938,1.216217,2.135719,1.756035,87.0,0.084675,2023-24,1,Attention,Critique,Normal,Normal,Attention,Normal
3,RFF,BARNSLEY HOSPITAL NHS FOUNDATION TRUST,2.069401,0.9660,1640.0,512.637363,92.407288,7.592712,78.0,0.098423,3.644835,2.914826,79250.0,211.120000,424.83765,1037.80683,0.828729,2.024446,2.442832,42.0,0.081929,2023-24,1,Attention,Critique,Normal,Normal,Normal,Attention
4,R1H,BARTS HEALTH NHS TRUST,1.671262,0.9913,3425.0,2072.923077,94.929388,5.070612,175.0,0.085393,5.373930,1.356528,204935.0,231.440000,2960.47284,5037.31642,1.428163,2.430055,1.701524,235.0,0.113366,2023-24,1,Attention,Critique,Normal,Attention,Normal,Normal
5,RC9,BEDFORDSHIRE HOSPITALS NHS FOUNDATION TRUST,1.580976,0.9684,3015.0,1200.611111,93.497756,6.502244,116.0,0.060827,3.398034,6.559870,190705.0,180.340000,1263.02456,2163.72522,1.051985,1.802187,1.713130,101.0,0.084124,2023-24,0,Critique,Critique,Normal,Normal,Normal,Critique
6,RXL,BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST,2.004938,1.0344,2355.0,777.000000,95.939582,4.060418,124.0,0.105568,5.374062,1.468585,117460.0,328.640000,638.20668,2287.60991,0.821373,2.944157,3.584434,66.0,0.084942,2023-24,1,Attention,Critique,Attention,Attention,Attention,Normal
7,RMC,BOLTON NHS FOUNDATION TRUST,2.113680,1.1497,1705.0,695.725275,89.783766,10.216234,191.0,0.236782,4.061010,7.915453,80665.0,210.880000,591.17191,1717.79153,0.849720,2.469066,2.905739,61.0,0.087678,2023-24,1,Attention,Attention,Attention,Normal,Normal,Critique
8,RAE,BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST,1.400389,1.1629,1835.0,705.494505,92.129283,7.870717,48.0,0.036631,3.094164,12.946923,131035.0,215.080000,795.67263,1495.52967,1.127823,2.119832,1.879579,84.0,0.119065,2023-24,0,Critique,Critique,Critique,Normal,Normal,Critique
9,RXQ,BUCKINGHAMSHIRE HEALTHCARE NHS TRUST,1.332233,0.9016,1615.0,567.000000,95.596643,4.403357,78.0,0.064343,3.364101,7.593318,121225.0,301.840000,789.15589,1892.68901,1.391809,3.338076,2.398372,86.0,0.151675,2023-24,0,Critique,Critique,Normal,Normal,Attention,Critique
10,RWY,CALDERDALE AND HUDDERSFIELD NHS FOUNDATION TRUST,2.229913,1.1280,2545.0,747.813187,88.028097,11.971903,92.0,0.080610,4.068825,2.497152,114130.0,192.080000,691.06804,1586.91021,0.924119,2.122068,2.296315,69.0,0.092269,2023-24,1,Attention,Attention,Attention,Normal,Normal,Attention
11,RGT,CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION ...,1.570068,0.9639,2350.0,1115.571429,93.917275,6.082725,198.0,0.132287,6.444772,0.791715,149675.0,175.400000,1678.08741,3317.51139,1.504240,2.973822,1.976960,107.0,0.095915,2023-24,1,Attention,Critique,Normal,Attention,Normal,Normal
12,RQM,CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATIO...,1.053430,0.7142,1735.0,875.901099,98.928576,1.071424,63.0,0.038251,4.010396,1.651488,164700.0,206.160000,1359.31711,2110.25321,1.551907,2.409237,1.552436,110.0,0.125585,2023-24,1,Attention,Critique,Normal,Normal,Normal,Normal
13,RFS,CHESTERFIELD ROYAL HOSPITAL NHS FOUNDATION TRUST,2.062087,0.9509,1840.0,550.362637,92.374658,7.625342,103.0,0.115432,3.170322,5.200045,89230.0,210.120000,465.95847,1121.31655,0.846639,2.037414,2.406473,44.0,0.079947,2023-24,0,Critique,Critique,Normal,Normal,Normal,Critique
14,RJR,COUNTESS OF CHESTER HOSPITAL NHS FOUNDATION TRUST,1.893439,0.9550,1505.0,517.285714,88.887473,11.112527,122.0,0.153488,4.388778,7.070516,79485.0,230.300000,525.28929,1192.80672,1.015472,2.305895,2.270762,47.0,0.090859,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
15,RXP,COUNTY DURHAM AND DARLINGTON NHS FOUNDATION TRUST,2.476053,1.2371,3270.0,1004.989011,93.853741,6.146259,152.0,0.115095,4.358714,1.166092,132065.0,230.880000,900.90559,2309.83871,0.896433,2.298372,2.563908,95.0,0.094528,2023-24,0,Critique,Critique,Critique,Normal,Normal,Normal
16,RJ6,CROYDON HEALTH SERVICES NHS TRUST,2.145958,1.0996,1310.0,564.076923,92.482126,7.517874,48.0,0.078631,6.420046,1.507085,61045.0,155.480000,598.15426,1277.73467,1.060413,2.265178,2.136129,46.0,0.081549,2023-24,1,Attention,Critique,Attention,Attention,Normal,Normal
17,RP5,DONCASTER AND BASSETLAW TEACHING HOSPITALS NHS...,2.014554,1.1290,2630.0,809.582418,91.851721,8.148279,145.0,0.111069,3.810171,1.283033,130550.0,178.520000,754.77613,1562.56029,0.932303,1.930082,2.070230,88.0,0.108698,2023-24,1,Attention,Attention,Attention,Normal,Normal,Normal
18,RBD,DORSET COUNTY HOSPITAL NHS FOUNDATION TRUST,2.190090,1.1057,1295.0,367.329670,89.095641,10.904359,91.0,0.153898,3.936158,0.963978,59130.0,102.240000,379.31800,810.91406,1.032636,2.207592,2.137821,30.0,0.081671,2023-24,1,Attention,Attention,Attention,Normal,Normal,Normal
19,RWH,EAST AND NORTH HERTFORDSHIRE NHS TRUST,1.499830,0.9141,1980.0,645.923077,87.657156,12.342844,143.0,0.108321,4.226275,1.227133,132015.0,174.720000,936.86256,1624.09900,1.450424,2.514385,1.733551,68.0,0.105276,2023-24,2,Normal,Attention,Normal,Normal,Normal,Normal
20,RJN,EAST CHESHIRE NHS TRUST,3.294207,1.2166,870.0,333.010989,91.789863,8.210137,20.0,0.075729,6.276542,0.851950,26410.0,230.240000,274.50578,664.41620,0.824314,1.995178,2.420409,32.0,0.096093,2023-24,1,Attention,Attention,Critique,Attention,Normal,Normal
21,RVV,EAST KENT HOSPITALS UNIVERSITY NHS FOUNDATION ...,2.412433,1.0510,3640.0,1150.296703,93.550637,6.449363,281.0,0.186235,4.714139,1.110117,150885.0,158.880000,1224.02398,2790.34039,1.064094,2.425757,2.279645,121.0,0.105190,2023-24,1,Attention,Critique,Attention,Attention,Normal,Normal
22,RXR,EAST LANCASHIRE HOSPITALS NHS TRUST,1.927123,1.3193,2290.0,1004.912088,94.023861,5.976139,166.0,0.139695,5.911377,1.889254,118830.0,144.380000,923.36997,2477.18005,0.918856,2.465071,2.682760,82.0,0.081599,2023-24,0,Critique,Critique,Critique,Attention,Normal,Normal
23,RDE,EAST SUFFOLK AND NORTH ESSEX NHS FOUNDATION TRUST,2.141251,1.1052,4475.0,1267.538462,94.790457,5.209543,225.0,0.107661,4.405638,1.189052,208990.0,167.400000,1220.30690,2864.02459,0.962738,2.259517,2.346971,90.0,0.071004,2023-24,1,Attention,Critique,Attention,Normal,Normal,Normal
24,RXC,EAST SUSSEX HEALTHCARE NHS TRUST,2.281978,1.0042,2635.0,804.659341,90.265487,9.734513,115.0,0.099593,4.668385,1.095523,115470.0,201.580000,740.68914,2003.17885,0.920500,2.489474,2.704480,74.0,0.091964,2023-24,1,Attention,Attention,Attention,Attention,Normal,Normal
25,RDU,FRIMLEY HEALTH NHS FOUNDATION TRUST,2.195413,1.0215,3585.0,1438.758242,92.181903,7.818097,157.0,0.096145,5.873092,3.582473,163295.0,266.780000,1297.64937,2869.80919,0.901923,1.994643,2.211544,180.0,0.125108,2023-24,1,Attention,Critique,Attention,Attention,Attention,Attention
26,RLT,GEORGE ELIOT HOSPITAL NHS TRUST,2.259093,1.0463,1205.0,406.714286,99.173219,0.826781,62.0,0.116235,4.300708,1.115486,53340.0,173.840000,354.23750,691.24980,0.870974,1.699596,1.951374,29.0,0.071303,2023-24,1,Attention,Critique,Attention,Normal,Normal,Normal
27,RTE,GLOUCESTERSHIRE HOSPITALS NHS FOUNDATION TRUST,1.753853,1.1578,2885.0,909.373626,93.818955,6.181045,205.0,0.124624,4.303186,5.577677,164495.0,205.680000,996.93337,2101.72296,1.096286,2.311177,2.108188,105.0,0.115464,2023-24,0,Critique,Critique,Critique,Normal,Normal,Critique
28,RN3,GREAT WESTERN HOSPITALS NHS FOUNDATION TRUST,1.787699,1.0043,1850.0,610.032967,94.334660,5.665340,113.0,0.109195,3.836814,4.256656,103485.0,194.840000,661.52253,1510.37676,1.084405,2.475894,2.283183,47.0,0.077045,2023-24,1,Attention,Critique,Attention,Normal,Normal,Attention
29,RCD,HARROGATE AND DISTRICT NHS FOUNDATION TRUST,1.422656,0.9834,1065.0,314.076923,91.025506,8.974494,52.0,0.069463,3.709291,0.774780,74860.0,139.380000,393.62876,1587.87425,1.253288,5.055686,4.033939,46.0,0.146461,2023-24,2,Normal,Attention,Normal,Normal,Normal,Normal
30,RQX,HOMERTON HEALTHCARE NHS FOUNDATION TRUST,0.838457,0.8697,600.0,335.857143,85.286130,14.713870,42.0,0.058692,3.001081,13.464226,71560.0,237.360000,560.91497,1129.99509,1.670100,3.364511,2.014557,41.0,0.122076,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
31,RWA,HULL UNIVERSITY TEACHING HOSPITALS NHS TRUST,2.083395,1.1476,3520.0,1250.945055,88.978003,11.021997,101.0,0.059779,4.697842,2.263916,168955.0,266.800000,1287.94007,2410.00570,1.029574,1.926548,1.871210,126.0,0.100724,2023-24,1,Attention,Attention,Attention,Attention,Attention,Attention
32,RYJ,IMPERIAL COLLEGE HEALTHCARE NHS TRUST,0.950226,0.7332,2100.0,1118.417582,88.344993,11.655007,130.0,0.058824,4.203913,7.531674,221000.0,181.660000,2107.97358,3859.84847,1.884782,3.451169,1.831071,135.0,0.120706,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
33,RGP,JAMES PAGET UNIVERSITY HOSPITALS NHS FOUNDATIO...,2.458355,1.1185,1675.0,452.000000,87.299426,12.700574,49.0,0.071916,5.237157,0.983342,68135.0,213.740000,418.51535,981.09052,0.925919,2.170554,2.344216,37.0,0.081858,2023-24,1,Attention,Attention,Attention,Attention,Normal,Normal
34,RNQ,KETTERING GENERAL HOSPITAL NHS FOUNDATION TRUST,1.891014,1.0488,1775.0,596.000000,95.160041,4.839959,93.0,0.099078,4.360995,4.437224,93865.0,227.880000,529.92650,1195.33329,0.889138,2.005593,2.255659,47.0,0.078859,2023-24,1,Attention,Critique,Attention,Normal,Normal,Attention
35,RJZ,KING'S COLLEGE HOSPITAL NHS FOUNDATION TRUST,1.631335,1.0115,3005.0,1454.733333,92.068802,7.931198,182.0,0.098803,5.767131,7.220217,184205.0,206.860000,2511.10016,4417.45876,1.726158,3.036611,1.759173,177.0,0.121672,2023-24,0,Critique,Critique,Attention,Attention,Normal,Critique
36,RAX,KINGSTON HOSPITAL NHS FOUNDATION TRUST,1.414356,0.8281,1130.0,465.000000,89.013352,10.986648,54.0,0.067589,3.390205,13.530258,79895.0,222.740000,588.83318,1082.37995,1.266308,2.327699,1.838178,57.0,0.122581,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
37,RXN,LANCASHIRE TEACHING HOSPITALS NHS FOUNDATION T...,1.813811,0.9392,2490.0,956.230769,93.489778,6.510222,304.0,0.221445,4.279451,5.579837,137280.0,201.360000,1032.77292,2427.21652,1.080046,2.538317,2.350194,103.0,0.107715,2023-24,0,Critique,Critique,Normal,Normal,Normal,Critique
38,RR8,LEEDS TEACHING HOSPITALS NHS TRUST,2.458544,1.1313,4055.0,1886.659341,94.298894,5.701106,262.0,0.158850,6.726851,1.870434,164935.0,225.760000,2449.25193,4305.43560,1.298195,2.282042,1.757857,169.0,0.089576,2023-24,1,Attention,Critique,Attention,Attention,Normal,Normal
39,RJ2,LEWISHAM AND GREENWICH NHS TRUST,1.856290,1.0090,2440.0,1058.758242,93.706083,6.293917,57.0,0.043364,4.477368,6.595915,131445.0,227.180000,1008.31694,2147.85949,0.952358,2.028659,2.130143,76.0,0.071782,2023-24,0,Critique,Critique,Attention,Normal,Normal,Critique
40,REM,LIVERPOOL UNIVERSITY HOSPITALS NHS FOUNDATION ...,2.107332,0.9709,3860.0,1608.054945,92.663992,7.336008,241.0,0.131572,5.702484,0.013649,183170.0,239.480000,1670.23110,3768.64749,1.038665,2.343606,2.256363,141.0,0.087684,2023-24,1,Attention,Critique,Normal,Attention,Normal,Normal
41,R1K,LONDON NORTH WEST UNIVERSITY HEALTHCARE NHS TRUST,1.549652,0.8607,2695.0,1089.978022,93.685728,6.314272,106.0,0.060951,3.878259,2.760048,173910.0,251.800000,1507.70484,2654.89645,1.383243,2.435734,1.760886,105.0,0.096332,2023-24,1,Attention,Critique,Normal,Normal,Attention,Attention
42,RWF,MAIDSTONE AND TUNBRIDGE WELLS NHS TRUST,1.601637,0.9332,2465.0,765.021978,86.147062,13.852938,183.0,0.118905,2.740721,1.211786,153905.0,110.104167,941.65666,1754.07448,1.230888,2.292842,1.862754,79.0,0.103265,2023-24,2,Normal,Attention,Normal,Normal,Normal,Normal
43,RPA,MEDWAY NHS FOUNDATION TRUST,2.385126,1.1932,1905.0,615.307692,84.110514,15.889486,74.0,0.092651,4.782567,1.621385,79870.0,199.000000,734.24025,1303.88663,1.193290,2.119081,1.775831,51.0,0.082885,2023-24,1,Attention,Normal,Critique,Attention,Normal,Normal
44,RBN,MERSEY AND WEST LANCASHIRE TEACHING HOSPITALS ...,2.092432,1.0579,3785.0,1304.857143,93.816847,6.183153,218.0,0.120515,3.671136,4.386644,180890.0,183.200000,1255.64031,2590.11839,0.962282,1.984982,2.062787,68.0,0.052113,2023-24,1,Attention,Critique,Attention,Normal,Normal,Attention
45,RAJ,MID AND SOUTH ESSEX NHS FOUNDATION TRUST,2.092894,1.0758,6225.0,1868.846154,93.647723,6.352277,433.0,0.145578,4.204157,5.165835,297435.0,219.080000,2115.25877,4173.31988,1.131853,2.233100,1.972959,169.0,0.090430,2023-24,0,Critique,Critique,Attention,Normal,Normal,Critique
46,RBT,MID CHESHIRE HOSPITALS NHS FOUNDATION TRUST,1.908305,0.9085,1590.0,540.461538,88.654386,11.345614,58.0,0.069611,3.534684,7.345175,83320.0,161.640000,459.13409,1335.67989,0.849522,2.471369,2.909128,53.0,0.098064,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
47,RD8,MILTON KEYNES UNIVERSITY HOSPITAL NHS FOUNDATI...,2.004536,1.1031,1370.0,586.483516,92.008619,7.991381,64.0,0.093643,5.082615,1.967957,68345.0,217.340000,518.36540,1027.03329,0.883853,1.751172,1.981292,69.0,0.117650,2023-24,1,Attention,Critique,Attention,Attention,Normal,Normal
48,RM1,NORFOLK AND NORWICH UNIVERSITY HOSPITALS NHS F...,2.117858,1.1986,3655.0,1067.714286,94.615179,5.384821,176.0,0.101982,5.159172,4.719550,172580.0,212.900000,1231.41217,2228.26230,1.153316,2.086946,1.809518,85.0,0.079609,2023-24,0,Critique,Critique,Critique,Attention,Normal,Attention
49,RNN,NORTH CUMBRIA INTEGRATED CARE NHS FOUNDATION T...,2.879828,1.0597,2140.0,680.406593,90.453349,9.546651,126.0,0.169560,5.624817,1.090028,74310.0,176.980000,629.35160,1810.11720,0.924964,2.660346,2.876162,63.0,0.092592,2023-24,1,Attention,Attention,Attention,Attention,Normal,Normal
50,RAP,NORTH MIDDLESEX UNIVERSITY HOSPITAL NHS TRUST,2.114271,1.0318,1260.0,457.010989,96.924594,3.075406,40.0,0.067120,7.059913,1.149425,59595.0,212.740000,633.13764,1351.97415,1.385388,2.958297,2.135356,46.0,0.100654,2023-24,0,Critique,Critique,Attention,Critique,Normal,Normal
51,RVW,NORTH TEES AND HARTLEPOOL NHS FOUNDATION TRUST,2.023996,0.9760,1940.0,598.824176,88.504946,11.495054,105.0,0.109546,3.263449,1.371935,95850.0,81.400000,521.52535,1375.74980,0.870916,2.297419,2.637935,46.0,0.076817,2023-24,2,Normal,Attention,Normal,Normal,Normal,Normal
52,RGN,NORTH WEST ANGLIA NHS FOUNDATION TRUST,2.137233,1.0031,2850.0,1097.802198,83.584585,16.415415,191.0,0.143232,4.316513,1.398575,133350.0,214.280000,936.40610,2000.18850,0.852983,1.821994,2.136027,80.0,0.072873,2023-24,2,Normal,Normal,Attention,Normal,Normal,Normal
53,RNS,NORTHAMPTON GENERAL HOSPITAL NHS TRUST,1.674339,0.9378,2055.0,780.879121,84.784689,15.215311,159.0,0.129547,3.334773,7.373610,122735.0,173.800000,737.15950,1426.87665,0.944012,1.827270,1.935642,53.0,0.067872,2023-24,1,Attention,Normal,Normal,Normal,Normal,Critique
54,RM3,NORTHERN CARE ALLIANCE NHS FOUNDATION TRUST,1.978691,1.0023,4550.0,1595.307692,83.134605,16.865395,303.0,0.131768,4.457058,1.352468,229950.0,211.440000,1959.01461,5200.53630,1.227985,3.259895,2.654669,153.0,0.095906,2023-24,2,Normal,Normal,Attention,Normal,Normal,Normal
55,RTF,NORTHUMBRIA HEALTHCARE NHS FOUNDATION TRUST,1.902401,0.9406,3185.0,910.747253,86.838485,13.161515,142.0,0.084817,2.796159,7.233305,167420.0,90.960000,753.23989,2137.32533,0.827057,2.346782,2.837509,92.0,0.101016,2023-24,1,Attention,Attention,Normal,Normal,Normal,Critique
56,RX1,NOTTINGHAM UNIVERSITY HOSPITALS NHS TRUST,1.688063,1.0489,4405.0,1805.197802,88.120994,11.879006,216.0,0.082774,4.346287,5.646676,260950.0,254.720000,2273.79854,4820.17651,1.259584,2.670165,2.119878,131.0,0.072568,2023-24,1,Attention,Attention,Attention,Normal,Attention,Critique
57,RTH,OXFORD UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,1.497331,0.8571,3100.0,1112.088889,93.769483,6.230517,198.0,0.095636,3.660104,1.618084,207035.0,225.480000,2062.43222,3914.16737,1.854557,3.519653,1.897840,154.0,0.138478,2023-24,1,Attention,Critique,Normal,Normal,Normal,Normal
58,RHU,PORTSMOUTH HOSPITALS UNIVERSITY NATIONAL HEALT...,1.939668,0.8934,3215.0,1170.164835,95.053763,4.946237,179.0,0.107994,4.558471,1.037707,165750.0,206.380000,1189.03870,2477.00548,1.016129,2.116800,2.083200,89.0,0.076058,2023-24,1,Attention,Critique,Normal,Attention,Normal,Normal
59,RHW,ROYAL BERKSHIRE NHS FOUNDATION TRUST,1.970280,1.0209,2075.0,675.000000,95.265771,4.734229,108.0,0.102549,3.469070,7.586764,105315.0,166.240000,828.69635,1763.73111,1.227698,2.612935,2.128320,71.0,0.105185,2023-24,0,Critique,Critique,Attention,Normal,Normal,Critique
60,RH8,ROYAL DEVON UNIVERSITY HEALTHCARE NHS FOUNDATI...,1.706619,0.9690,3460.0,1192.648352,88.399628,11.600372,151.0,0.074480,4.120633,1.398343,202740.0,221.280000,1270.65243,2957.66692,1.065404,2.479915,2.327676,100.0,0.083847,2023-24,2,Normal,Attention,Normal,Normal,Normal,Normal
61,RAL,ROYAL FREE LONDON NHS FOUNDATION TRUST,1.377631,0.7671,2490.0,1203.109890,76.687705,23.312295,153.0,0.084650,4.291176,10.506515,180745.0,208.840000,1791.87443,3036.97448,1.489369,2.524270,1.694859,155.0,0.128833,2023-24,1,Attention,Normal,Normal,Normal,Normal,Critique
62,RD1,ROYAL UNITED HOSPITALS BATH NHS FOUNDATION TRUST,1.995814,0.9294,1955.0,607.626374,93.802221,6.197779,151.0,0.154152,3.722486,1.612986,97955.0,226.020000,727.80228,1625.20602,1.197779,2.674680,2.233032,60.0,0.098745,2023-24,1,Attention,Critique,Normal,Normal,Normal,Normal
63,RNZ,SALISBURY NHS FOUNDATION TRUST,1.676217,0.9559,980.0,482.109890,91.643873,8.356127,49.0,0.083811,5.117211,1.180193,58465.0,224.580000,455.38944,1001.02303,0.944576,2.076338,2.198169,54.0,0.112008,2023-24,1,Attention,Attention,Normal,Attention,Normal,Normal
64,RHQ,SHEFFIELD TEACHING HOSPITALS NHS FOUNDATION TRUST,1.394106,0.9654,3600.0,1607.175824,88.085031,11.914969,200.0,0.077450,4.518248,4.495992,258230.0,174.340000,1726.69314,4066.29820,1.074365,2.530089,2.354963,123.0,0.076532,2023-24,1,Attention,Attention,Normal,Attention,Normal,Attention
65,RK5,SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST,2.166274,1.0596,2250.0,719.472527,91.561278,8.438722,109.0,0.104944,4.034590,7.090935,103865.0,179.920000,673.46375,1377.40830,0.936052,1.914470,2.045260,155.0,0.215436,2023-24,1,Attention,Attention,Attention,Normal,Normal,Critique
66,RH5,SOMERSET NHS FOUNDATION TRUST,2.164603,1.0193,3260.0,1438.384615,89.907023,10.092977,155.0,0.102918,5.768417,3.250224,150605.0,139.640000,1122.65833,3067.34623,0.780499,2.132494,2.732217,101.0,0.070218,2023-24,1,Attention,Attention,Attention,Attention,Normal,Attention
67,RTR,SOUTH TEES HOSPITALS NHS FOUNDATION TRUST,1.583424,1.0701,2755.0,997.758242,88.723072,11.276928,197.0,0.113225,3.639341,9.879878,173990.0,167.800000,1128.11169,2715.72092,1.130646,2.721823,2.407316,89.0,0.089200,2023-24,1,Attention,Attention,Attention,Normal,Normal,Critique
68,R0B,SOUTH TYNESIDE AND SUNDERLAND NHS FOUNDATION T...,2.044218,1.0962,3250.0,1142.956044,85.766616,14.233384,111.0,0.069818,4.735155,0.993804,158985.0,159.320000,944.42700,2842.48678,0.826302,2.486961,3.009747,60.0,0.052495,2023-24,1,Attention,Attention,Attention,Attention,Normal,Normal

In [30]:
# ============================================
# CELLULE — CHEMINS NOUVELLES ANNÉES
# ============================================
DATA = r'C:\Users\hp\healthsim-simulation\data'

# ── 2021-22 ──
paths_2122 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2021-22-Final-GHVBN.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr21-Mar22.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_march_2022.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2021-22-tab.xlsx',
    'aeqi'      : rf'{DATA}\ECDS_CQI_Open_Data_M12.csv',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2022 England and Organisation.xlsx',
    'nidc'      : None,
}

# ── 2019-20 ──
paths_1920 = {
    'beds'      : rf'{DATA}\1920-Q4-Beds-Open-Overnight-Web_File-Final-DE5WC.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr19-Mar20.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_march_2020.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-prov-2019-20-tab.xlsx',
    'aeqi'      : rf'{DATA}\AE_CQI_M12.xls',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2020 England and Organisation.xlsx',
    'nidc'      : None,
}

# ── 2018-19 ──
paths_1819 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Final_Q4_2018-19.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr18-Mar19.zip',
    'cdi'       : rf'{DATA}\Table_2_Monthly_CDI_2P_April_2018.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-prov-2018-19-tab.xlsx',
    'aeqi'      : rf'{DATA}\2018-19 M12 AE CQI Suppressed.xlsx',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2019 England and Organisation.xlsx',
    'nidc'      : None,
}

# ── 2017-18 ──
paths_1718 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Q4-201718-REVISED-Web_File-Final.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr17-Mar18.zip',
    'cdi'       : rf'{DATA}\cdi_table_trust_20190425.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-prov-2017-18-tab.xlsx',
    'aeqi'      : rf'{DATA}\HESF_AE_CQI_dev_NHSdigital_M12 suppressed v1.1.xlsx',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2018 Organisation - Excel tables.xlsx',
    'nidc'      : None,
}

# ── 2024-25 ──
paths_2425 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2024-25.xlsx',
    'shmi'      : rf'{DATA}\SHMI data, Apr24-Mar25.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_april_2023_to_march_2024-os.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2024-25-tab.xlsx',
    'aeqi'      : rf'{DATA}\aeqi_open_data_2025_03.csv',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2025 England and Organisation.xlsx',
    'nidc'      : rf'{DATA}\National-Imaging-Data-Collection-Asset-Count-2024-25-v1-FINAL.xlsx',
}

print("✅ Chemins définis !")

✅ Chemins définis !

In [32]:
# ============================================
# CELLULE — CHARGEMENT TOUTES LES ANNÉES
# ============================================

# Chargement des nouvelles années
print("Chargement 2021-22...")
df_2122 = charger_annee('2021-22', paths_2122)

print("\nChargement 2019-20...")
df_1920 = charger_annee('2019-20', paths_1920)

print("\nChargement 2018-19...")
df_1819 = charger_annee('2018-19', paths_1819)

print("\nChargement 2017-18...")
df_1718 = charger_annee('2017-18', paths_1718)

print("\nChargement 2024-25...")
df_2425 = charger_annee('2024-25', paths_2425)

# Combinaison avec les années existantes
df_final = pd.concat([
    df_2324,   # 2023-24 ✅
    df_2223,   # 2022-23 ✅
    df_2122,   # 2021-22
    df_1920,   # 2019-20
    df_1819,   # 2018-19
    df_1718,   # 2017-18
    df_2425,   # 2024-25
], ignore_index=True)

print(f"\n{'='*50}")
print(f"✅ Dataset final : {len(df_final)} trusts × {len(df_final.columns)} colonnes")
print(f"\nDistribution par année :")
print(df_final['annee'].value_counts().sort_index())

Chargement 2021-22...

==================================================
Chargement année 2021-22...
==================================================
✅ Beds : 188 trusts
  Fichier SHMI trouvé : SHMI data at trust level, Apr21-Mar22 (csv).csv
✅ SHMI : 121 trusts
✅ CDI : 138 trusts

KeyError: "None of [Index(['Hospital provider code and description†', 'Unnamed: 1', 'Admissions',\n       'Emergency', 'Mean length of stay', 'FCE bed days', 'Emergency.1',\n       'Elective', 'Other'],\n      dtype='str')] are in the [columns]"

In [ ]:
# Voir toutes les colonnes du fichier ERIC
import pandas as pd

DATA = r'C:\Users\hp\healthsim-simulation\data'
df_eric = pd.read_csv(rf'{DATA}\ERIC - 2023_24 - Trust data.csv', nrows=2)

# Afficher toutes les colonnes liées aux équipements
cols_equip = [col for col in df_eric.columns 
              if any(word in col.lower() for word in 
                     ['equip', 'medical', 'maintain', 'operational', 
                      'backlog', 'condemn', 'replac', 'asset'])]

print(f"Total colonnes : {len(df_eric.columns)}")
print(f"\nColonnes liées équipements ({len(cols_equip)}) :")
for col in cols_equip:
    print(f"  - {col}")

print(f"\nToutes les colonnes :")
for col in df_eric.columns:
    print(f"  - {col}")

In [ ]:
# ============================================
# CHEMINS — TOUTES LES NOUVELLES ANNÉES
# ============================================
DATA = r'C:\Users\hp\healthsim-simulation\data'

# ── 2012-13 ──
paths_1213 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2012-13-Revised-Final-79659.xls',
    'shmi'      : rf'{DATA}\SHMI data files, Apr12-Mar13.zip',
    'cdi'       : rf'{DATA}\Clostridium_difficile_monthly_data_April_acute_trusts_table_2.xls',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2012-13-tab.xlsx',
    'aeqi'      : rf'{DATA}\prov-ae-qual-indi-eng-mar13-tab1.xls',
    'workforce' : rf'{DATA}\nhs-work-stat-mar-2014-org-tab.xls',
}

# ── 2013-14 ──
paths_1314 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2013-14-Final-Working-Revised-33335.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr13-Mar14.zip',
    'cdi'       : rf'{DATA}\Clostridium_difficile_monthly_data_April_acute_trusts_table_2.xls',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2013-14-tab.xlsx',
    'aeqi'      : rf'{DATA}\prov-ae-qual-indi-eng-march 2014-tab1.xls',
    'workforce' : rf'{DATA}\nhs-work-stat-mar-2014-org-tab.xls',
}

# ── 2014-15 ──
paths_1415 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2014-15-Revised-Nov15-Final-41885.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr14-Mar15.zip',
    'cdi'       : rf'{DATA}\Table_2_Monthly_CDI_2P_Mar_2015.xlsx',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2014-15-tab.xlsx',
    'aeqi'      : rf'{DATA}\prov-ae-qual-indi-eng-march 2015-tab1.xls',
    'workforce' : rf'{DATA}\nhs-work-stat-mar-2015-org-tab.xls',
}

# ── 2015-16 ──
paths_1516 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2015-16-Revised-Aug16-Final-84398.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr15-Mar16.zip',
    'cdi'       : rf'{DATA}\Table_2_Monthly_CDI_2P_March_2016.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2015-16-tab.xlsx',
    'aeqi'      : rf'{DATA}\prov-ae-qual-indi-eng-march 2016-tab1.xls',
    'workforce' : rf'{DATA}\nhs-work-stat-mar-2016-org-tab.xlsx',
}

# ── 2016-17 ──
paths_1617 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2016-17-Final-98123.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr16-Mar17.zip',
    'cdi'       : rf'{DATA}\Table_2_Monthly_CDI_2P_March_2017.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2016-17-tab.xlsx',
    'aeqi'      : rf'{DATA}\ae_cqi_2016_17_m131.xlsx',
    'workforce' : rf'{DATA}\nhs-work-stat-mar-2017-org-tab.xlsx',
}

# ── 2017-18 ──
paths_1718 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Q4-201718-REVISED-Web_File-Final.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr17-Mar18.zip',
    'cdi'       : rf'{DATA}\cdi_table_trust_20190425.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-prov-2017-18-tab.xlsx',
    'aeqi'      : rf'{DATA}\HESF_AE_CQI_dev_NHSdigital_M12 suppressed v1.1.xlsx',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2018 Organisation - Excel tables.xlsx',
}

# ── 2018-19 ──
paths_1819 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Final_Q4_2018-19.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr18-Mar19.zip',
    'cdi'       : rf'{DATA}\Table_2_Monthly_CDI_2P_April_2018.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-prov-2018-19-tab.xlsx',
    'aeqi'      : rf'{DATA}\2018-19 M12 AE CQI Suppressed.xlsx',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2019 England and Organisation.xlsx',
}

# ── 2019-20 ──
paths_1920 = {
    'beds'      : rf'{DATA}\1920-Q4-Beds-Open-Overnight-Web_File-Final-DE5WC.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr19-Mar20.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_march_2020.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-prov-2019-20-tab.xlsx',
    'aeqi'      : rf'{DATA}\AE_CQI_M12.xls',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2020 England and Organisation.xlsx',
}

# ── 2021-22 ──
paths_2122 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2021-22-Final-GHVBN.xlsx',
    'shmi'      : rf'{DATA}\SHMI data files, Apr21-Mar22.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_march_2022.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2021-22-tab.xlsx',
    'aeqi'      : rf'{DATA}\ECDS_CQI_Open_Data_M12.csv',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2022 England and Organisation.xlsx',
}

# ── 2024-25 ──
paths_2425 = {
    'beds'      : rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2024-25.xlsx',
    'shmi'      : rf'{DATA}\SHMI data, Apr24-Mar25.zip',
    'cdi'       : rf'{DATA}\Table_6_CDI_april_2023_to_march_2024-os.ods',
    'prov'      : rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2024-25-tab.xlsx',
    'aeqi'      : rf'{DATA}\aeqi_open_data_2025_03.csv',
    'workforce' : rf'{DATA}\NHS Workforce Statistics, March 2025 England and Organisation.xlsx',
}

print("✅ Chemins définis pour 10 nouvelles années !")

In [ ]:
# ============================================
# TEST — Chargement 2016-17 d'abord
# ============================================
print("Test chargement 2016-17...")
try:
    df_1617 = charger_annee('2016-17', paths_1617)
    print(f"✅ 2016-17 : {len(df_1617)} trusts chargés")
    print(df_1617.head(3))
except Exception as e:
    print(f"❌ Erreur : {e}")

In [36]:
# Voir les colonnes exactes de l'onglet Hospital Providers 2021-22
df_test = pd.read_excel(
    rf'{DATA}\hosp-epis-stat-admi-hosp-prov-2021-22-tab.xlsx',
    sheet_name='Hospital Providers',
    header=None
)
# Afficher les 10 premières lignes pour voir la structure
print(df_test.iloc[:10, :10].to_string())

    0                                                                                                                                                                        1    2   3   4   5   6   7    8    9
0 NaN                                                                                                                                                                      NaN  NaN NaN NaN NaN NaN NaN  NaN  NaN
1 NaN                                                                                                                                                                      NaN  NaN NaN NaN NaN NaN NaN  NaN  NaN
2 NaN                                                                                                                                                                      NaN  NaN NaN NaN NaN NaN NaN  NaN  NaN
3 NaN                                                                                                                                                       Hospital Providers  NaN NaN NaN NaN NaN NaN  NaN  NaN
4 NaN  The hospital providers table contains episodes grouped according to the organisation that provided the admitted patient care (normally an NHS trust) within Area Teams.  NaN NaN NaN NaN NaN NaN  NaN  NaN
5 NaN                                                                                                                                                                      NaN  NaN NaN NaN NaN NaN NaN  NaN  NaN
6 NaN                                                                   The NHS Digital, Hospital Episode Statistics for England. Admitted Patient Care statistics, 2021-22 .   NaN NaN NaN NaN NaN NaN  NaN  NaN
7 NaN                                                                       Activity in English NHS Hospitals and English NHS commissioned activity in the independent sector.  NaN NaN NaN NaN NaN NaN  NaN  NaN
8 NaN                                                                     For more information on data quality please see the data quality note accompanying this publication.  NaN NaN NaN NaN NaN NaN  NaN  NaN
9 NaN                                                                                                                                                                      NaN  NaN NaN NaN NaN NaN NaN  NaN  NaN

In [38]:
# Chercher la ligne des headers
for i in range(10, 20):
    print(f"Ligne {i} : {df_test.iloc[i, :10].tolist()}")

Ligne 10 : [nan, 'Hospital provider code and description†', nan, nan, nan, nan, nan, nan, 'Finished consultant episodes', 'Admissions']
Ligne 11 : [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Ligne 12 : [nan, 'Total', nan, nan, nan, nan, nan, nan, 19626344, 15979490]
Ligne 13 : [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Ligne 14 : [nan, 'Y56', 'LONDON COMMISSIONING REGION', nan, nan, nan, nan, nan, 3002355, 2466175]
Ligne 15 : [nan, 'Y58', 'SOUTH WEST COMMISSIONING REGION', nan, nan, nan, nan, nan, 2012960, 1622950]
Ligne 16 : [nan, 'Y59', 'SOUTH EAST COMMISSIONING REGION', nan, nan, nan, nan, nan, 2787390, 2246695]
Ligne 17 : [nan, 'Y60', 'MIDLANDS COMMISSIONING REGION', nan, nan, nan, nan, nan, 3693755, 3011930]
Ligne 18 : [nan, 'Y61', 'EAST OF ENGLAND COMMISSIONING REGION', nan, nan, nan, nan, nan, 2181730, 1737645]
Ligne 19 : [nan, 'Y62', 'NORTH WEST COMMISSIONING REGION', nan, nan, nan, nan, nan, 2710910, 2222220]

In [40]:
# Voir toutes les colonnes header ligne 10
print("Headers ligne 10 :")
for i, val in enumerate(df_test.iloc[10, :].tolist()):
    if val is not None and str(val) != 'nan':
        print(f"  Col {i} : {val}")

Headers ligne 10 :
  Col 1 : Hospital provider code and description†
  Col 8 : Finished consultant episodes
  Col 9 : Admissions
  Col 10 : Male
  Col 11 : Female
  Col 12 : Gender Unknown
  Col 13 : Emergency
  Col 14 : Waiting list
  Col 15 : Planned
  Col 16 : Other Admission Method
  Col 17 : Mean time waited
  Col 18 : Median time waited
  Col 19 : Mean length of stay
  Col 20 : Median length of stay
  Col 21 : Mean age
  Col 22 : Age 0
  Col 23 : Age 1-4
  Col 24 : Age 5-9
  Col 25 : Age 10-14
  Col 26 : Age 15
  Col 27 : Age 16
  Col 28 : Age 17
  Col 29 : Age 18
  Col 30 : Age 19
  Col 31 : Age 20-24
  Col 32 : Age 25-29
  Col 33 : Age 30-34
  Col 34 : Age 35-39
  Col 35 : Age 40-44
  Col 36 : Age 45-49
  Col 37 : Age 50-54
  Col 38 : Age 55-59
  Col 39 : Age 60-64
  Col 40 : Age 65-69
  Col 41 : Age 70-74
  Col 42 : Age 75-79
  Col 43 : Age 80-84
  Col 44 : Age 85-89
  Col 45 : Age 90+
  Col 46 : Day case
  Col 47 : FCE bed days
  Col 48 : Emergency
  Col 49 : Elective
  Col 50 : Other

In [44]:
pip install xlrd --break-system-packages

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
   ---------------------------------------- 0.0/96.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/96.6 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/96.6 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/96.6 kB ? eta -:--:--
   ------------ --------------------------- 30.7/96.6 kB 259.2 kB/s eta 0:00:01
   ---------------- ----------------------- 41.0/96.6 kB 279.3 kB/s eta 0:00:01
   -------------------------------------- - 92.2/96.6 kB 435.7 kB/s eta 0:00:01
   ---------------------------------------- 96.6/96.6 kB 423.1 kB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [46]:
import pandas as pd
DATA = r'C:\Users\hp\healthsim-simulation\data'

# Voir structure Beds 2012-13
df = pd.read_excel(rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2012-13-Revised-Final-79659.xls',
                   sheet_name=None)
print("Onglets Beds 2012-13 :")
for s in df.keys():
    print(f"  - {s}")

Onglets Beds 2012-13 :
  - NHS Trust by Sector
  - SHA by Sector
  - Occupied by Specialty
  - Data Quality

In [48]:
df_beds = pd.read_excel(
    rf'{DATA}\Beds-Open-Overnight-Web_File-Q4-2012-13-Revised-Final-79659.xls',
    sheet_name='NHS Trust by Sector',
    header=None
)
print(f"Shape : {df_beds.shape}")
print("\nLignes 0-15 colonnes 0-8 :")
print(df_beds.iloc[:15, :8].to_string())

Shape : (249, 23)

Lignes 0-15 colonnes 0-8 :
     0                    1                                                                                                              2         3         4         5          6                7
0  NaN                  NaN                                                                                                            NaN       NaN       NaN       NaN        NaN              NaN
1  NaN               Title:                                   Average daily number of available and occupied beds open overnight by sector       NaN       NaN       NaN        NaN              NaN
2  NaN             Summary:  KH03 is the collection of data to monitor available and occupied beds open overnight that are consultant led.       NaN       NaN       NaN        NaN              NaN
3  NaN                  NaN                                                                                                            NaN       NaN       NaN       NaN        NaN              NaN
4  NaN              Period:                                                                                          January to March 2013       NaN       NaN       NaN        NaN              NaN
5  NaN              Source:                                                                     NHS England: Unify2 data collection - KH03       NaN       NaN       NaN        NaN              NaN
6  NaN               Basis:                                                                                                       Provider       NaN       NaN       NaN        NaN              NaN
7  NaN           Published:                                                                                                  23rd May 2013       NaN       NaN       NaN        NaN              NaN
8  NaN             Revised:                                                                                             21st November 2013       NaN       NaN       NaN        NaN              NaN
9  NaN              Status:                                                                                                        Revised       NaN       NaN       NaN        NaN              NaN
10 NaN             Contact:                                                                              Emma Noble - Unify2@dh.gsi.gov.uk       NaN       NaN       NaN        NaN              NaN
11 NaN                  NaN                                                                                                            NaN       NaN       NaN       NaN        NaN              NaN
12 NaN  Provider Level Data                                                                                                            NaN       NaN       NaN       NaN        NaN              NaN
13 NaN                  NaN                                                                                                            NaN       NaN       NaN       NaN  Available              NaN
14 NaN                 Year                                                                                                         Period  SHA Code  Org Code  Org Name     Total   General & Acute

In [50]:
print("Headers ligne 14 :")
for i, val in enumerate(df_beds.iloc[14, :].tolist()):
    if str(val) != 'nan':
        print(f"  Col {i} : {val}")

print("\nLignes 15-20 :")
print(df_beds.iloc[15:20, :10].to_string())

Headers ligne 14 :
  Col 1 : Year
  Col 2 : Period
  Col 3 : SHA Code
  Col 4 : Org Code
  Col 5 : Org Name
  Col 6 : Total
  Col 7 : General & Acute
  Col 8 : Learning Disabilities
  Col 9 : Maternity
  Col 10 : Mental Illness
  Col 12 : Total
  Col 13 : General & Acute
  Col 14 : Learning Disabilities
  Col 15 : Maternity
  Col 16 : Mental Illness
  Col 18 : Total
  Col 19 : General & Acute
  Col 20 : Learning Disabilities
  Col 21 : Maternity
  Col 22 : Mental Illness

Lignes 15-20 :
     0        1      2    3    4                                               5              6              7            8            9
15 NaN  2012-13  March  NaN  NaN                                         England  138178.305556  106374.472222  1696.577778  7839.322222
16 NaN      NaN    NaN  NaN  NaN                                             NaN            NaN            NaN          NaN          NaN
17 NaN  2012-13  March  Q30  RE9             SOUTH TYNESIDE NHS FOUNDATION TRUST            415            376            6           33
18 NaN  2012-13  March  Q30  RLN  CITY HOSPITALS SUNDERLAND NHS FOUNDATION TRUST     887.122222     852.744444            0    34.377778
19 NaN  2012-13  March  Q30  RR7           GATESHEAD HEALTH NHS FOUNDATION TRUST            517            461            0           16